---
title: "著作権法［司法試験対策］"
date: 6/3/2024
categories: [知的財産法, 司法試験対策]
---

分割前の記事は [こちら](知的財産法［司法試験］.qmd) ．

## H30：無効審判に引き続く訴訟・審判手続


* 無効審決取消訴訟（181条1項）における主張事由
    * 無効審決において無効原因とされた点に限定されるか?（審理範囲）
    * 最大判昭和51年3月10日民集30巻2号79頁（メリヤス編機事件）
* 共同出願違反（38条） [{{< fa arrow-right >}}]{.color-minty} 123条1項2号、2項の適用
* 無効審決取消判決後の再度の審判（181条2項）における**判決の拘束力**
    * 進歩性欠如を理由とした無効審決を取り消した後、新たな証拠の下に、再度進歩性を否定することは可能か?
    * 最判平成4年4月28日民集46巻4号245頁（高速旋回式バレル研磨法事件）
    * 最判昭和55年1月24日民集34巻1号80頁（食品包装容器事件）
* 再度の審判請求を不成立とする審決がなされた後、侵害訴訟で同一事由に係る無効の抗弁（104条の3第1項）が提出できるか？（一事不再理・167条）

## H29：実施許諾、間接侵害


* 専用実施許諾をした後の特許権者による侵害訴訟
    * 68条但書の解釈
    * 最高裁判所平成17年6月17日判決民集59巻5号1074頁【リガンド分子安定複合体事件】
* 先使用による通常実施権（79条）
    * 「事業の準備」の意味：即時実施の意思＋それが客観的に認識される態様・程度において表明
* 専用実施権者（77条1項）による差止請求（100条1項）
* 間接侵害（101条2号該当性）
    * 従属説or独立説？（直接実施は69条3項によって非侵害）
    * 薬剤の服用行為の「生産」性
* 独占的通常実施権（78条1項）者による差止請求＋損害賠償請求
    * 排他的に実施する権利を有するか?（専用実施権者の差止請求権の代位行使は?）
    * 102条2項の類推適用の可能性
    * 特許権者/権利者による実施行為の要否：知財高裁平成25年2月1日判決判時2179号36頁【ごみ貯蔵機器事件】

## H28：機能的クレーム、訂正の抗弁


* 機能的クレームの技術的範囲（70条1項）の確定
    * **明細書の発明の詳細な説明の記載を参酌し**，そこに開示された実施例，あるいは実施例としては記載されていなくても，**明細書に開示された発明に関する記述の内容から当該発明の属する技術の分野における通常の知識を有する者（当業者）が実施し得る構成に限られるべき**であるとする考え方（東京地裁平成10年12月22日判決判例時報1674号152頁【磁気媒体リーダー事件】，知財高裁平成25年6月6日判決【パソコン等の器具の盗難防止用連結具事件】等）
* 無効の抗弁
    * サポート要件（36条6項1号）、実施可能要件（4項1号）違反
* 訂正の対抗主張：無効審判における訂正請求（134条の2第1項）と無効の抗弁（104条の3）に対する訂正の再抗弁
    * 訂正審判請求・訂正請求の要否
    * 要件に関する議論（以下裁判例の傾向）
    * ①当該請求項について**訂正審判請求ないし訂正請求をした**こと，②当該訂正が**法の定める訂正要件を充たす**こと，③当該訂正により当該請求項について無効の抗弁で主張された**無効理由が解消する**こと，④被告製品が**訂正後の請求項の技術的範囲に属する**こと
* 無効審決取消訴訟（181条1項）の原告適格（cf. 132条2項・共同審判）
    * 一方共有者のみによる提起の問題点
    * 最高裁判所平成14年2月22日民集56巻2号348頁【ETNIES事件】で問題となった，**権利の形成過程と権利成立後における共有者の関係性**の違い
* 侵害訴訟後の無効審判における主張制限（104条の4）
    * 125条に基づく遡及効との関係

## H27


* 無効審判（123条1項各号）
    * 新規性喪失事由（29条1項1号・2号）
* 技術的範囲（70条1項）の解釈と均等論
* 補償金請求（65条1項）の可否
* 102条2項に基づく損害額の推定
    * 権利者の実施の要否
