---
title: "刑法各論［期末試験対策］（２）"
date: 1/28/2024
categories: [刑法, 期末試験対策]
---

<!-- 
					<wfw:commentRss>https://dragoman8.wordpress.com/2024/01/28/%e5%88%91%e6%b3%95%e5%90%84%e8%ab%96%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/feed/</wfw:commentRss>
			<slash:comments>0</slash:comments>
		
		
		
		<media:content url="https://0.gravatar.com/avatar/6efd6e6d120f53814883fd3d6d5f6d193f7a9e42949739c9d8a86f3b3c52476b?s=96&#38;d=identicon&#38;r=G" medium="image">
			<media:title type="html">tldhfl</media:title>
		</media:content>
	</item>
		<item>
		<title>民事実務　[期末試験対策]</title>
		<link>https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/</link>
					<comments>https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#respond</comments>
		
		<dc:creator><![CDATA[tldhfl]]></dc:creator>
		<pubDate>Tue, 23 Jan 2024 05:04:29 +0000</pubDate>
				<category><![CDATA[日々の勉強]]></category>
		<guid isPermaLink="false">http://dragoman8.wordpress.com/?p=100</guid>

					<description><![CDATA[書き方 訴訟物 請求原因事実以下の要件事実 執行不奏功の場合の代償請求 執行不奏効の場合の代償請求（民執 31Ⅱ）「第1項の引渡しの執行が目的を達することができ ないときは、被告は、原告に対し、350万円を支払え。」「よ [&#8230;]]]></description>
										<content:encoded><![CDATA[ -->
<h1 class="wp-block-heading" id="書き方">書き方</h1>



<ol><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#書き方">書き方</a><ol><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#訴訟物">訴訟物</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#請求原因事実以下の要件事実">請求原因事実以下の要件事実</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#執行不奏功の場合の代償請求">執行不奏功の場合の代償請求</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#付随的申立て">付随的申立て</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#売買契約に基づく請求">売買契約に基づく請求</a><ol><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#弁済の抗弁-473条">【弁済の抗弁】473条</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#同時履行の抗弁-533条">【同時履行の抗弁】533条</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#代物弁済-482条">【代物弁済】482条</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#相殺の抗弁-505条1項">【相殺の抗弁】505条1項</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#債務不履行解除-541条-催告解除">【債務不履行解除】541条（催告解除）</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#手付解除-557条1項">【手付解除】557条1項</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#即時取得による所有権喪失の抗弁-192条">【即時取得による所有権喪失の抗弁】192条</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#無権代理人の責任-117条1項">無権代理人の責任（117条1項）</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#貸金-保証に関する請求">貸金・保証に関する請求</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#不動産明渡しに関する請求">不動産明渡しに関する請求</a><ol><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#建物収去土地明渡請求">建物収去土地明渡請求</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#抗弁-建物所有権喪失">【抗弁：建物所有権喪失】</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#再抗弁-登記名義保有">【再抗弁：登記名義保有】</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#不動産登記に関する請求">不動産登記に関する請求</a><ol><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#登記上利害関係を有する第三者に対する承諾請求">登記上利害関係を有する第三者に対する承諾請求</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#賃貸借契約に関する請求">賃貸借契約に関する請求</a><ol><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#抗弁-建物使用継続による法定更新-借地借家法26条２項">抗弁【建物使用継続による法定更新】借地借家法26条２項</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#抗弁">抗弁【非背信性の評価根拠事実】</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#建物収去土地明渡請求-1">建物収去土地明渡請求</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#抗弁-土地使用継続による法定更新-借地借家法上の期間満了に対する抗弁">抗弁【土地使用継続による法定更新（借地借家法上の期間満了に対する抗弁）】</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#二段の推定に関して">二段の推定に関して</a><ol><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#認否の仕方">認否の仕方</a></li><li><a class="wp-block-table-of-contents__entry" href="https://dragoman8.wordpress.com/2024/01/23/%e6%b0%91%e4%ba%8b%e5%ae%9f%e5%8b%99%e3%80%80%e6%9c%9f%e6%9c%ab%e8%a9%a6%e9%a8%93%e5%af%be%e7%ad%96/#二段の推定">二段の推定</a></li></ol></li></ol>



<h2 class="wp-block-heading" id="訴訟物">訴訟物</h2>



<ul>
<li>訴訟物の特定は原告の権能であり、訴訟物は原告が選択する（民事訴訟法246条、処分権主義）。</li>



<li>債権は、<strong>①権利の主体・相手方並びに②権利の給付内容及び③発生原因</strong>によって特定される。</li>



<li>物権に基づく請求における訴訟物は、①権利の主体及び相手方、②物権の種類、③物権的請求権の種別、④具体的給付によって特定される。</li>



<li>契約に基づく請求の場合の訴訟物の個数は、<span style="text-decoration: underline">契約の個数</span>によって定まる。</li>



<li>物権的請求権の訴訟物の個数は、侵害されている物権の個数と侵害の個数によって決 せられる。</li>



<li>主たる請求と附帯請求は、<span style="text-decoration: underline">実体法上併存関係</span>にあり、原告が特に条件をつけることなく、2個の訴訟物について審判を求めた場合には、単純併合となる。</li>
</ul>



<h2 class="wp-block-heading" id="請求原因事実以下の要件事実">請求原因事実以下の要件事実</h2>



<ul>
<li>①訴訟物の確認、②法律要件、③要件事実（法律要件からの振り分け）、④事実関係の当てはめの順番で論じる。</li>



<li>抗弁：請求原因と両立し、請求原因から生じる法律効果を消滅・障害・阻止する事実の主張</li>
</ul>



<h2 class="wp-block-heading" id="執行不奏功の場合の代償請求">執行不奏功の場合の代償請求</h2>



<p>執行不奏効の場合の代償請求（民執 31Ⅱ）<br>「第1項の引渡しの執行が目的を達することができ ないときは、被告は、原告に対し、350万円を支払え。」<br>「よって、原告は、被告に対し、所有権に基づき本件機械の 引渡しを求めるとともに、同引渡しの執行が目的を達することができないときは、不法行為に基づき350万円の支払を求める。」</p>



<h2 class="wp-block-heading" id="付随的申立て">付随的申立て</h2>



<p>「訴訟費用は被告の負担とする。」<br>裁判所は職権でその負担の裁判をしなければならないため （法67条1項）、職権発動を促す意味があるにすぎない。しかし、当事者は、必ず申立てをすべきである。<br>「並びに <em>仮執行の宣言</em> を求める。」 → 仮執行宣言（法259条）の申立て</p>



<p>「3. 訴訟費用は被告らの負担とする<br>との判決並びに第３項につき仮執行宣言を求める。」</p>



<h1 class="wp-block-heading" id="売買契約に基づく請求">売買契約に基づく請求</h1>



<h2 class="wp-block-heading" id="弁済の抗弁-473条">【弁済の抗弁】473条</h2>



<p>e.g.,「被告は、原告に対し、本件売買代金支払債務の履行として、平成○年○月○日に1500万円を、平成○年○月○日に300万円を、平成○年○月○日に200万円を支払った。</p>



<h2 class="wp-block-heading" id="同時履行の抗弁-533条">【同時履行の抗弁】533条</h2>



<p>e.g., 「Yは、Xが甲土地の引き渡し及び所有権移転登記手続きをするまで、代金の支払いを拒絶する。」</p>



<p>同時履行の抗弁権の実体法上の要件<br>①同一の双務契約から生じた2つの対立した債権の存在<br>②相手方の債務が履行期にあること<br>③相手方が履行またはその提供をしないで請求をすること<br>④援用者から同時履行の抗弁権の行使があること<br>①については請求原因において売買契約締結の事実が主張・立証されることにより、代金支払債務に同時履行の抗弁権が付着していることが基礎付けられている。②については、売買契約においては請求原因における売買契約締結の主張・立証によって直ちに債務が履行期にあることが基礎付けられている。③については、債務を履行したことにつき、これによって利益を受ける債権者（すなわちX）が再抗弁として主張・立証すべきであるので要件事実とならない。以上から同時履行の抗弁権の要件事実は④同時履行の抗弁権の行使のみとなる。</p>



<h2 class="wp-block-heading" id="代物弁済-482条">【代物弁済】482条</h2>



<p>e.g., <br>「①XとYは平成30年8月15日、本件売買代金債務の弁済に代えて甲絵画の所有権を移転するとの合意をした。<br>②Yは、同日当時、甲絵画を所有していた。<br>③Yは、同日、Xに対し、①の合意に基づき、甲絵画を引き渡した。」<br><br>代物弁済の前提として本来の債務の存在が必要となるが、請求原因において主張・立証されているため記載する必要はない。①は代物弁済契約締結の事実であり、「弁済に代えて」「所有権を移転する」ことを内容とした合意である。②について、代物弁済が所有権の移転によって債務を消滅させるものであるところ、他人の物の給付では代物弁済の効果は生じないので、債務者が所有権を有していたことを記載する必要がある。③について、代物弁済による債務の消滅という効果が発生するためには、代物の給付が完了しなければならない。かかる給付の完了は、対抗要件の具備まで必要とし、不動産であれば登記の具備、動産であれば「引渡し」が要件事実となる。また、①の「合意」によって代物弁済契約自体は成立し、物の所有権の移転は契約の履行として行われるものであると解するため、「引渡し」は「合意に基づき」行われたことを摘示する必要がある。</p>



<h2 class="wp-block-heading" id="相殺の抗弁-505条1項">【相殺の抗弁】505条1項</h2>



<p>要件事実<br>①自働債権の発生原因事実<br>(②自働債権が双務契約である場合には、同時履行の抗弁権の発生障害または消滅原因となる事実)<br>(③自働債権が賃借型である場合には、弁済期の定めとその到来)<br>④相殺の意思表示</p>



<p>実体法上の要件<br>①相対立する債権の存在<br>②両債権が同種目的であること<br>③両債権が弁済期にあること<br>④債務の性質が相殺を許さないものでないこと<br>⑤相殺の意思表示<br><br>①について、受働債権の発生原因事実は既に請求原因で現れているため、抗弁では自働債権の発生原因事実を主張すれば足りる。<br>②について、両債権の発生原因事実が主張されれば、それらが同種目的であることは現れるところ、受働債権は請求原因で現れているので、自働債権の発生原因事実を主張・立証すれば同種の目的の要件も充足される。<br>③について、受働債権が弁済期にあることは請求原因に通常現れている。自働債権の弁済期については<strong>、売買型であれば</strong>契約成立と同時に直ちに履行すべきものであるため自働債権の発生原因事実を主張立証することで弁済期にあることも現れる。自働債権の発生原因が<strong>賃借型である場合</strong>には、一定期間、借主が利用することが予定されており、契約締結と同時に弁済期が到来するのではないため、自働債権の発生原因事実に加え、弁済期の到来の主張立証が必要となる。<br>④について、自働債権に同時履行の抗弁権が付着している場合は相殺が許されないところ、自働債権が売買契約等の<strong>双務契約の場合</strong>には、その発生原因事実を主張立証することで同時履行の抗弁権の存在が基礎付けられてしまう。そのため、かかる場合には自働債権の同時履行の抗弁権の発生障害または消滅原因となる事実を主張立証しなければ主張自体失当となる。また、受働債権が不法行為債権である場合のように債務の性質が相殺を許さないことが明白な場合は相殺の主張自体失当となるが、それ以外の場合は利益を受ける相殺の相手方が主張立証責任を負う。</p>



<h2 class="wp-block-heading" id="債務不履行解除-541条-催告解除">【債務不履行解除】541条（催告解除）</h2>



<p><strong>「履行遅滞」の要件</strong><br>・<strong>債務の発生原因</strong>（×請求原因で現れている）<br>・<strong>履行可能</strong>（×履行不能であれば債務者Xが再抗弁で主張すべき）<br>・<strong>履行期の経過</strong>（×412条３項の催告により遅滞が基礎づけられる）<br>・<strong>履行期に履行がない</strong>（×履行によって債務を免れ利益を受けるXが履行したことを再抗弁で主張立証すべき）<br>・<strong>遅滞の違法性・弁済の提供</strong><br>弁済の提供について、双務契約においては同時履行の抗弁権の存在は履行遅滞の違法性阻却事由に当たるため、解除を主張するYとしては、目的物引渡債務に付着している同時履行の抗弁の存在効果の消滅を主張しなければならないため、弁済の提供を主張する必要がある。</p>



<h2 class="wp-block-heading" id="手付解除-557条1項">【手付解除】557条1項</h2>



<p>要件事実<br>①手付金の合意とその引渡し(<strong>交付を指摘する必要</strong>）<br>②a)売主の解除の場合、契約を解除することを示して手付金倍額の現実の提供をしたこと<br>b)買主の解除の場合、契約を解除することを示して手付金返還請求権の放棄をしたこと<br>③売買契約解除の意思表示をした</p>



<h2 class="wp-block-heading" id="即時取得による所有権喪失の抗弁-192条">【即時取得による所有権喪失の抗弁】192条</h2>



<p>実体法上の成立要件<br>①取引行為②基づく引渡し③平穏かつ公然④善意⑤無過失</p>



<p>③④は民法186条１項により推定される暫定事実、⑤は188条の推定を受ける。よってこれらは即時取得の成立を争う者が主張・立証責任を負う。<br>そのため即時取得の要件事実は<span style="text-decoration: underline">①取引行為　②①に基づく引渡し</span>（現実の引渡し、簡易の引渡し、指図による占有移転によることは可能だが、占有改定の方法によることはできない。なぜならば占有改定は譲渡人が占有したままの状態であり外観上変化がないのに即時取得を認めることは相当でないからである。）</p>



<h2 class="wp-block-heading" id="無権代理人の責任-117条1項">無権代理人の責任（117条1項）</h2>



<p>117条１項の損賠請求の実体法上の要件<br>①YとZが契約を締結したこと<br>②Zは①の契約締結の際、Xのためであることを示したこと（顕名）<br>③Zは①の契約締結の代理権を有していなかったこと<br>④Xの追認を得ることができなかったこと<br>⑤Yが履行または損害賠償を選択したこと</p>



<p>③はZが自己の代理権を証明しなければならないことを規定しており、請求原因ではない。④はZにおいてXの追認を得たことを抗弁として主張・立証すべきである。⑤についてYがどちらかを選択して請求している以上、請求原因で改めて主張する必要はない。そのため、請求原因は①と②の二つである。</p>



<h1 class="wp-block-heading" id="貸金-保証に関する請求">貸金・保証に関する請求</h1>



<p>弁済期限の指摘<br>経過（履行遅滞に基づく損害賠償請求権が含まれる場合だけ「経過」で、元本請求及び利息請求のみの場合は「到来」となる）。</p>



<p>保証契約に基づく保証債務履行請求権について<br>仮に利息を併せて請求したとしても訴訟物は１個である。<br>なぜなら、保証債務は特約のない限りその対象として主たる債務に関する利息や遅延損害金を包含する(447条１項)ため、１個の保証契約に基づき、元本、利息、遅延損害金の保証債務の履行を請求する場合、これらは全てその保証契約に基づく保証債務履行請求権に含まれる。</p>



<h1 class="wp-block-heading" id="不動産明渡しに関する請求">不動産明渡しに関する請求</h1>



<h2 class="wp-block-heading" id="建物収去土地明渡請求">建物収去土地明渡請求</h2>



<p>訴訟物＝所有権に基づく返還請求権としての土地明渡請求権1個<br>「「被告は、原告に対し、別紙物件目録(省略)記載２の建物(以下「本件建物」という。)を収去して同目録（省略）記載１の土地（以下「本件土地」という。）を明け渡せ。」」</p>



<p>建物収去と土地明渡しを求めているが、土地上の建物所有によって土地所有権が侵害されている場合、土地所有者には、土地返還請求権のみが発生するのであり、<span style="text-decoration: underline">「建物収去」の判決主文は、執行方法の特定を明示する必要があるため記載するに過ぎない。</span>そのため、建物収去は、土地明渡の履行態様であり、土地明渡しと別個の実体法上の請求権の発現ではないため、訴訟物について記載する必要はない。</p>



<h2 class="wp-block-heading" id="抗弁-建物所有権喪失">【抗弁：建物所有権喪失】</h2>



<p>「Yは、平成30年10月12日、Aに対し、乙建物を代金200万円で売った。」</p>



<h2 class="wp-block-heading" id="再抗弁-登記名義保有">【再抗弁：登記名義保有】</h2>



<p>(1)乙建物には、平成30年10月12日当時、Y名義の所有権移転登記が存在していた。<br>(2)(1)の登記はYの意思に基づいてされた。<br>(3)乙建物に、Y名義の所有権移転登記が存在している。<br><br><span style="text-decoration: underline">被告が建物の所有権を取得し、自らの意思に基づいてその旨の登記をした場合</span>には、建物を他に譲渡したとしても、被告が引き続き登記名義を保有する限り、原告に対し、建物所有権の喪失を主張して建物収去土地明渡しの義務を免れることはできない（最判平成6.2.8）。そのため、被告に登記名義がある旨の主張は、建物所有権喪失の抗弁に基づく、所有権の喪失により所有者としての義務を免れるという法律効果の発生を障害するものであるから、再抗弁となる。</p>



<h1 class="wp-block-heading" id="不動産登記に関する請求">不動産登記に関する請求</h1>



<p>「被告は、甲土地について、別紙登記目録（省略）記載の所有権移転登記の抹消登記手続をせよ。」</p>



<p>真正な登記名義の回復を原因とする所有権移転登記請求の場合<br>「被告は、原告に対し、別紙物件目録（省略）記載の土地について<strong>真正な登記名義の回復を原因とする</strong>所有権移転登記手続をせよ。」</p>



<h2 class="wp-block-heading" id="登記上利害関係を有する第三者に対する承諾請求">登記上利害関係を有する第三者に対する承諾請求</h2>



<p><strong>請求の趣旨</strong><br>(1)被告Yは、別紙物件目録（省略）記載の土地につき、別紙登記目録（省略）記載の所有権移転登記の抹消登記手続をせよ。<br>(2)被告Zは、原告に対し、(1)の抹消登記手続を承諾せよ。</p>



<p><strong>請求原因</strong><br>(1)原告は、平成30年10月10日当時、甲土地を所有していた。<br>(2)甲土地について、被告Y名義の所有権移転登記がある。<br>(3)甲土地について、被告Zを抵当権者とする抵当権設定登記がある。<br>(4)平成30年11月11日当時、被告Yが甲土地の所有名義人であった。</p>



<p>XのYに対する上記請求が認められ、Y名義の所有権移転登記が抹消されると、その所有権移転登記を基礎とする抵当権設定登記等も抹消されることになる（不動産登記規則152条２項）ため、登記上利害関係を有する第三者が存在するときは、<strong>当該第三者の承諾があるときに限り、登記の抹消を申請することができる(不動産登記法68条)</strong>。本件で、Zは、抵当権設定登記の名義人であり、登記の抹消によって権利上の損害を受けるため、「登記上の利害関係を有する第三者」に当たる。そのため、XのYに対する甲土地の所有権移転登記抹消登記手続請求をするにあたって、Zの「承諾」が必要となる。</p>



<p>所有権移転登記を抹消する際、登記官の職権により、上記登記を前提として登記された抵当権設定登記は、当然に抹消される( <code>不動産登記規則152条2項</code> )。<br>権利に関する登記の抹消を申請する場合、 <em>登記上利害関係を有する第三者</em> が存在するときは、申請書に第三者の承諾書又はこれに対抗することができる裁判の謄本を添付しなければならない。 ( <code>不動産登記法68条</code> 、不動産登記令別表26ヘ)(添付しなければ申請が却下される。同法25条9号)</p>



<h1 class="wp-block-heading" id="賃貸借契約に関する請求">賃貸借契約に関する請求</h1>



<p>（賃貸借契約の終了原因が<strong>期間満了</strong>であるとき）<br>XがYに対して建物明渡しを請求する場合（建物の賃貸借の場合には借地借家法の適用がある）の請求原因事実</p>



<p>①建物賃貸借契約の締結<br>②①の契約に基づく引渡し<br>（③〜⑤は期間満了の場合の終了原因事実）<br>③賃貸借契約の存続期間の満了<br>④③の期間満了の１年前から６ヶ月前までの間に「更新拒絶の通知」(借地借家法26条１項)をしたこと<br>⑤④の更新拒絶の通知時から③の期間満了までの間に、更新を拒絶するについて「<strong>正当な事由</strong>」(借地借家法28条)が存在したことを基礎付ける評価根拠事実<br>※具体的要素としては、賃貸人及び賃借人が建物の使用を必要とする事情の他、従前の経過、建物の利用状況、建物の現況、立退料の申し出など。正当事由の存在時期については更新拒絶の通知をした時点で存在し、かつ、期間満了まで存続することが必要。</p>



<p>（賃貸借契約の終了原因が<strong>解約申し入れ</strong>である場合）<br>①建物賃貸借契約の締結<br>②①に基づく引渡し<br>③XのYに対する解約申し入れの意思表示<br>④③から６ヶ月の経過<br>⑤③の時点から④の時点まで、「解約申入れ」について「正当な事由」が存在していたことについての評価根拠事実</p>



<h2 class="wp-block-heading" id="抗弁-建物使用継続による法定更新-借地借家法26条２項">抗弁【建物使用継続による法定更新】借地借家法26条２項</h2>



<p>更新拒絶の通知をした場合であっても、建物の賃貸借期間が満了した後建物の賃借人が使用を継続する場合において、建物の賃貸人が遅滞なく異議を述べなかったときは、同一内容の契約を更新したものとみなす旨を規定している。</p>



<h2 class="wp-block-heading" id="抗弁">抗弁【非背信性の評価根拠事実】</h2>



<p>YZ間の転貸借契約はXに対する背信的行為と認めるに足りない特段の事情があること（判例は、無断転貸は原則として「背信的行為」に当たるが、賃借人側が「背信的行為と認めるに足りない特段の事情」を主張・立証した場合は解除権は発生しないとする。）</p>



<h2 class="wp-block-heading" id="建物収去土地明渡請求-1">建物収去土地明渡請求</h2>



<p>①所有権に基づく返還請求権の場合の訴訟物は、所有権に基づく返還請求権としての土地明渡請求権と記載するのに対して、②<strong>賃貸借契約</strong>に基づく目的物返還請求権の場合の訴訟物は、賃貸借契約に基づく目的物返還請求権としての<strong>建物収去</strong>土地明渡請求権となり、「建物収去」も訴訟物の要素となる。なぜなら、①の場合は建物収去は執行方法の明示にすぎないのに対し、②の場合は建物収去も目的物返還請求権の内容に含まれるからである。</p>



<h2 class="wp-block-heading" id="抗弁-土地使用継続による法定更新-借地借家法上の期間満了に対する抗弁">抗弁【土地使用継続による法定更新（借地借家法上の期間満了に対する抗弁）】</h2>



<p>借地借家法5条2項は、借地権の存続期間が満了した後、借地権者が土地の使用を継続するときも、建物がある場合に限り、従前の契約と同一の条件で契約を更新したものとみなす</p>



<p>「Yは、平成30年6月1日（借地借家法３条による30年の存続期間）以降も、乙建物を所有して甲土地を占有している。」<br>→【再抗弁】遅滞なき異議<br>①Xは、平成30年6月4日、Yに対して、甲土地の使用を中止するよう求めた。<br>②更新を拒絶するにうき正当な事由があることを基礎づける評価根拠事実（例：乙建物は老朽化している）</p>



<h1 class="wp-block-heading" id="二段の推定に関して">二段の推定に関して</h1>



<p>文書の成立の論証：認否を確認したあと、どこを争っているのかに沿って論証↓</p>



<h2 class="wp-block-heading" id="認否の仕方">認否の仕方</h2>



<ul>
<li>前提事実を争う。：「文書の成立は否認する。印影（署名）が名義人の印章（署名）によるものではない。」</li>



<li>（一段目）事実上の推定を争う：「文書の成立は否認する。印影が名義人の印章によるものであることは認めるが〇〇により盗用されたものである。」（→よって作成名義人の意思に基づく押印とは言えない）</li>



<li>（二段目）法228Ⅳの推定を争う：「文書の成立は否認する。印影（署名）が名義人の意思によるものであることは認めるが、文書（の〇〇の部分）は後に変造されたものである。」</li>
</ul>



<h2 class="wp-block-heading" id="二段の推定">二段の推定</h2>



<p>　本件文書は、【請求原因/抗弁…】における【例：保証契約の成立】という事実を直接【間接】に立証しうるものといえ、直接証拠【間接証拠】である。<br>　また、【保証書etc.】は一般的に（<span style="text-decoration: underline">紛争顕在化前に作成された、紛争当事者と利害関係にないものが作成した、事実があった時点に近い時期に作成された、記載行為が習慣化されている文書、自己に不利益な内容を記載した文書</span>）であるから、その記載及び体系から類型的にみて<strong>類型的信用文書</strong>にあたる。<br><br>→処分証書と認定するパターン<br>そして、<strong>処分証書</strong>とは、<span style="text-decoration: underline">意思表示その他の法律行為が文書によってされた場合のその文書</span>をいうところ（よってされた説）、本件文書は処分証書としての外観を有する文書である。<br>　したがって、審理の結果、（形式的証拠能力が認められ）意思表示その他の法律行為が文書によってされたと認められる場合には、処分証書として特段の事情を考慮するまでもなく実質的証拠力が認められ、請求原因○○の事実を認定することができる。<br><br>→類型的信用文書と認定するパターン<br>　したがって成立の申請成立の真正が認められ形式的証拠力が認められれば特段の事情がない限り実質的証拠力が認められる。</p>



<p>そこで、本件文書の成立の真正を検討する。被告は、本件文書の成立を否認しており原告がこれを主張・立証する事になるが、他方で、被告は、本件文書の印影について作成名義人である被告の印章によって顕出されたものであることを認めているため、いわゆる二段の推定（法228Ⅳ参照）が働き、特段の事情についての反証がなければ、成立の真正が認められる。</p>



<p>【印章の盗用ver.】一段目の推定を争っている場合<br>　本件で被告は、【上記印章が盗用され、本件文書が偽造された】と主張しているため、被告の意思に基づく押印がない、と一段目の推定を争っていると解される。そこで、裁判所はかかる事情の主張・立証を被告に求めるべきである。その際、一段目の推定は、経験則に基づく事実上の推定にすぎず、立証責任の転換は生じないため、被告としては、上記押印が被告の意思によるものであることについて真偽不明に持ち込めば足りる。</p>



<p>【変造ver.】<br>　本件で被告は、【本件文書は署名押印後に変造された】と主張しているため、文書全体が被告の意思に基づくわけではない、と二段目の推定を争っていると解される。そこで、裁判所はかかる事情の主張・立証を被告に求めるべきである。その際、法228Ⅳの「推定」は、法定証拠法則を定めたものであって、証明責任を転換したものではないため、被告としては、本件文書が署名押印後に変造されたことについて真偽不明に持ち込めば足りる。</p>


