---
title: "刑事訴訟法［司法試験対策］"
date: 3/9/2024
categories: [刑訴法, 司法試験対策]
---

## R5


* 領置（刑訴法221条）
    * 「被疑者その他の者が遺留した物」（遺留物）
    
    「所有者、所持者若しくは保管者が任意に提出した物」（任意提出物）
    * 占有取得の過程に強制の要素がない
    
    but　占有を継続する時点で強制処分の性質を有する
    * 「遺留物」＞遺失物
    
    自己の意思によらずに占有を喪失した場合に限られず、自己の意思によって占有を放棄し、離脱させた物も含むと定義する必要がある（ここでの占有は物理的な支配）
        * 被疑者は占有を放棄していたとしても、その場の管理者の占有が及んでいるのではないか？
    
    * （遺留物に当たるかどうかの問題とは別に）
    
    プライバシーの利益が法的に保護されるか？
    
    → 具体的状況下における必要性・相当性の判断
    * 最決平成20年4月15日刑62巻5号1398頁

    > ダウンベスト等の領置手続についてみると，被告人及びその妻は，これらを入れたごみ袋を不要物として公道上のごみ集積所に排出し，その占有を放棄していたものであって，排出されたごみについては，通常，そのまま収集されて他人にその内容が見られることはないという期待があるとしても，捜査の必要がある場合には，刑訴法２２１条により，これを遺留物として領置することができるというべきである。また，市区町村がその処理のためにこれを収集することが予定されているからといっても，それは廃棄物の適正な処理のためのものであるから，これを遺留物として領置することが妨げられるものではない。

    * 実況見分調書の証拠能力（伝聞法則）
        * 誰の公判期日外の供述を問題にしているのか？
        * 供述書面の性質（321条3項適用の理由）
        * 最決平成17年9月27日刑集59巻7号753頁

## R4


* おとり捜査の適法性
    * 最決平成16年7月12日刑集58巻5号333頁
    * おとり捜査の意義（正確に）
    * 法的性質から限界を導く
* 訴因変更の要否
    * 最決平成13年4月11日刑集55巻3号127頁
    * 最決平成24年2月29日刑集66巻4号589頁
    * 検察官の釈明内容が訴因となるか？（訴因の特定に不可欠な事項か？）
    * 最判昭和58年12月13日刑集37巻10号1581頁（被告人の謀議への関与について、審理における争点として顕在化させることなく認定した事例）

## R3


* 令状に基づく捜索差押え
    * ①令状に明記された物件に当てはまること（憲法35条、法219条1項）

    ②被疑事実との関連性（憲法35条、222条1項・99条1項）
    * 最判昭和51年11月18日判時837号104頁：情状事実や背景事情に関する物も被疑事実との関連性が認められる証拠に含めるべきか？
    * 可視性・可読性のない電磁的記録媒体について、無愛用を確認せずに差押えができるか？
        最決平成10年5月1日刑集52巻4号275頁
* 伝聞法則（320条1項）
    * 犯行メモの位置付け（要証事実の考え方）

    > ①そのメモの内容が客観的な犯罪事実と一致している場合，偶然の一致は考えにくいような事項の一致が認められ，かつ，それが犯罪発生前に作成されたことが判明していれば，そこから直ちに犯罪がそのメモに記載された犯行計画にのっとって遂行されたことを推認でき，かかる一致の認められるメモの作成者が判明していれば，そのこと自体から，メモの作成者と犯行の実行者の間で当該メモに記載された内容の共謀が推認し得るとする考え方，
    > ②犯行計画を記載したメモは，その作成者が作成当時に有していた犯行計画ないし犯罪意思を述べたものとて，心理状態の供述に当たり，原供述者の原供述時における心理状態を立証する上では，内心の状態について知覚と記憶の過程は問題にならないため，供述者の外界の事実の存在を示す典型的な供述証拠に比べて誤りの危険は小さく，また，真摯性，叙述の点について誤りの有無・程度を吟味する必要はあるものの，それは原供述者の尋問によらなくても，その記載内容や作成状況等から誤りの有無・程度の吟味が可能であることなどから，非伝聞証拠として，刑事訴訟法第３２０条第１項の適用はなく，かつ，その記載内容が客観的な犯罪事実と一致し，当該犯罪をメモの作成者以外の者が実行した場合には，作成者と実行者の間で当該メモに記載された内容の共謀が形成されたことを推認し得るとする考え方^[出題趣旨 より．]

## R2


* 任意取り調べ（198条1項）の適法性
    * 最決昭和59年2月29日刑集38巻3号279頁（高輪グリーン・マンション殺人事件）の規範
    
    事案の性質、被疑者に対する容疑の程度、被疑者の態度等の諸般の事情を考慮
    * 「強制手段に当たるか」と「任意手段の限界を超えていないか」という二段階で示す。
    * 比較衡量説と行為規範説への意識
* 自白法則（319条1項）
    * 供述証拠である自白に対しても、違法収集証拠排除法則の適用があるか？（二元説）
    
    cf. 東京高判平成14年9月4日判時1808号144頁（ロザール事件控訴審判決）
    * 仮に適用があるとしても、同様の基準が適用されるか？
* 類似事実による犯人性の証明の可否（前科証拠）

## R1

* 別件逮捕・勾留の適法性
    * 本件基準説、別件基準説
    * どの事実を考慮に入れるべきか？
* 訴因変更の
    * 公訴事実の同一性（312条1項）
    * 公判前整理手続の後に行う訴因変更の許否
    
    cf. 「公判前整理手続を経た後の公判においては，充実した公判審理のための争点整理や審理計画の策定がされた趣旨を没却するような訴因変更は許されない」とした下級審裁判例として，東京高判平成20年11月18日高刑集61巻4号6頁がある。

