---
title: "刑事訴訟法（訴訟）"
date: 3/4/2024
categories: [刑訴法, まとめ]
---

## 公訴の提起

* 審判対象を選択するのは、検察官（訴追裁量権・起訴独占主義、刑訴法248条）。
    * 裁判所も検察官の訴因選択に拘束されて、訴因に記載された犯罪事実に限って審判する。それに応じて、被告人・弁護人も審判対象たる訴因以外の事実については、主張することができない。
* 訴因外の事実について審理するか？
    * 訴因記載の犯罪の成立を妨げる事情は、訴因外の事実であっても審理の対象となる（実体法的解釈に依存する）。
    * 単独正犯を訴因とする事件で、訴因外の事実として共謀者がいる場合
    
    > 「[被告人1人の行為により犯罪構成要件のすべてが満たされたと認められるとき]{.underline} は、 他に共謀共同正犯者が存在するとしてもその犯罪の成否は左右されない」
    
    [{{< fa arrow-left >}}]{.color-minty} この意味で、刑法60条には、①実行行為の全部を行っていない者が正犯として責任を負うために適用される場合と②単独正犯としても責任を問い得るが、他人との共謀があるために適用される場合とがある。
* 量刑上の不利益をもたらす一部起訴　e.g., かすがい現象
    * 被告人の不利益になるような訴因の設定は [検察官の訴追権を逸脱して違法である]{.underline} とする見解
        * 訴因変更が必要となるとする立場が一方である。
        * 罪数判断のために考慮するだけであれば、その事実について被告人を有罪として処罰するわけでないから、訴因変更手続を経なくとも訴因外の事実を考慮できるとする立場もある。
    * このような一部起訴も許されるとする見解
    [{{< fa arrow-right >}}]{.color-minty} 訴因外の事実は考慮できないため、量刑の場面で、一罪として処罰する場合の処断刑の範囲内で刑を言い渡さなければならない。

## 訴因の特定・明示

* 起訴状の記載事項である「公訴事実」（256条2項）
    * 公訴事実は訴因を明示して記載しなければならない。
* 訴因：訴因には六何の原則に従った事項だけではなく、構成要件の修正形式である共犯や未遂に該当する事実も含まれる。
    * 犯罪の主体・客体・行為と結果
    [{{< fa arrow-right >}}]{.color-minty} それ自体「罪となるべき事実」であると共に、その具体的記載によって訴因が特定される。
    * 日時・場所・方法
    [{{< fa arrow-right >}}]{.color-minty} 犯罪の構成要素となっている場合を除き、「罪となるべき事実」には当たらない。しかし、訴因を特定する手段となる。
* 特定の趣旨（識別説と防御権説）
    * ①裁判所に対して審判の対象を限定する
    * ②被告人に対して防御の範囲を示す
* 訴因の特定の判断基準

    【絶対的要請】
    1. 「罪となるべき事実」の記載

        cf. 有罪判決の場面と共通の問題
        
        ①特定の構成要件
        
        ②全ての構成要件要素　
        
        ③事実の具体性（反証をおよそ不可能にするか）
        
    2. 他の犯罪との識別　「特定」できているか？

    【相対的要請】

    「できる限り」＝特殊事情の存在

    「犯罪の種類、性質等のいかんにより、これを詳らかにできない特殊事情がある場合」
* 特別な構成要件（？）からの要請
    * 過失犯における「過失の態様」の位置付け
    
        [{{< fa arrow-right >}}]{.color-minty} ②の問題とするか、③の問題とするか（構成要件要素と捉えるかどうかによる）
    * 連続的包括一罪：「単一の意思」と「共通ないし類似した態様の行為」が構成要件とされる
        * 被害者を明示し、一定期間内に行われた実行行為をまとめて一罪として構成することによって、他の犯罪と区別することができる。
        * 構成要件であると解すると、個々の傷害行為について特定されていないとしても、共通ないし類似した傷害行為が継続して行われていたことが示されていれば、構成要件要素については十分に示されていると言える。訴因の記載の仕方からしておよそ証明不可能であると言えるほどまでに不明確であるわけでもない。
    * 共同正犯
        * 共謀の日時、場所は訴因の特定に不可欠な事実ではない。
        * 実行行為者が誰かは共同正犯の成否に関係ない。
    * 覚醒剤使用等の罪
        * 最終行為説、最低一行為説による特定

## 訴因変更

### 訴因変更の要否

* 第1段階：訴因の特定のために不可欠な事項か？（裁判所が審判対象を変更し、検察官の訴因設定権を奪ってはならない）
    * 訴因の識別機能とリンクする
    * 第一段階には例外はない
* 第2段階：被告人の防御にとって重要なのか？（争点明確化のために書き込まれた事項について、被告人の不意打ち防止を図る）
    * 一般的に被告人の防御にとって重要な事項については、争点の明確化などのために実行行為者を明示するのが望ましい。明示した場合には、原則としてそれと異なる事実認定をする場合に訴因変更手続を要する。
    * 第2段階の例外：ただし、被告人の防御の具体的な状況等の審理の経過に照らし、
        * ①被告人に不意打ちを与えるものではないと認められ、かつ、
        * ②判決で認定される事実が被告人にとってより不利益であるとは言えない場合には、例外的に、訴因変更手続を経る必要がない。
    * 訴因の防御範囲を示す機能とリンクするとも。しかし、訴因の機能は両者一体となっていると解する立場に立てば、第２段階では異なる立場になるのではないか。むしろ、訴訟全般で要求される争点の明確化に伴う不意打ち防止の要請が趣旨なのではないか。
* 「訴因の記載として不可欠な事項」について異なる事実認定をした場合（第一段階の問題）には、不告不利原則違反として378条3号の絶対的控訴理由に該当するのに対して、訴因の記載として必須ではない事項について（第二段階の問題）は、379条違反として相対的控訴理由となる。

### 訴因変更の可否

* 「公訴事実の同一性を害しない限度において」（刑訴312条1項）検察官の訴因変更請求を許さなければならない。
* ①公訴事実の単一性＋②（狭義の）公訴事実の同一性
    * 単一性は、訴訟係属中2つの時点で比較する場合と特定の時点で2つの事実を比較する場合とで同様に問題になる。両事実が実体法上の一罪を構成すれば、公訴事実の同一性が認められる。
    * 狭義の同一性は、両事実が実体法上の一罪を構成しないけれども、公訴事実の同一性が認められる場合。
    
        [{{< fa arrow-right >}}]{.color-minty} 基本的事実関係の同一性によって判断
    （事実上の共通性が弱い場合にも、非両立性を相補的に考慮）
* 「非両立性」の意味
    * 事実の両立可能性（香城説）
    
        [{{< fa arrow-right >}}]{.color-minty} 同一の社会的事実に帰属するものか
    * 実体法上の両立可能性（大澤説）

        [{{< fa arrow-right >}}]{.color-minty} 同一刑罰権に対する二重処罰に当たるかどうか

### 訴因変更の許否

* [公訴事実の同一性の範囲内であったとしても]{.underline} 、訴因変更に制約を課すべき場合がないか？
* 訴因変更に伴い、被告人に重大な不利益が生じる場合：訴因変更の時機
    * 被告人に十分な防御の準備をさせるために公判手続を停止（312条4項）
    * 訴因変更によって、被告人が新たな訴因につき防御を強いられることになるとしても、そのことだけで訴因変更が許されなくなるわけではなく、＋αが必要。
    
    [{{< fa arrow-right >}}]{.color-minty} ①訴因変更の時期・段階、②両訴因の関係（訴因の骨格となる事実関係の共通性）、③審理の経過（検察官の立証の経過、被告人側の防御の内容とその程度）、④被告人に対する不意打ちの程度、変更後に予想される被告人側の不利益・負担の程度、⑤事案の重大性
    などに鑑みて[、訴因変更請求が検察官の誠実な権利の行使と認められないような場合]{.underline} があり得る。
* 訴因変更により実体的真実の解明とそれに基づく処罰が妨げられる場合：変更前の訴因が成立する場合の訴因変更
    * 最高裁の判例はまだない。
    * 刑法312条1項+検察官に起訴猶予権限（248）・公訴取消権限（257）→訴因変更の場面でも、検察官がそもそも処罰を求めないのであれば裁判所はそれに従うべき？

### 訴因変更命令

* 訴因変更命令・勧告の義務が認められる場合があるか？
    * 仮にあると尽くさなかった場合には審理不尽によって当該措置は違法となる。
    * 当事者主義の構造
    
    but 重大な犯罪について訴因変更すれば有罪となることが明白であるような場合には、著しく正義に反する結果が生じるとして、訴因変更命令が義務的になる。
    * ただし、犯罪の重大性と証拠の明白性だけでなく、[検察官の訴追意思や被告人の防御上の利益などの手続上の要素、および事案の性質・内容、被告人の花校への関与の程度、共犯者との処分の均衡]{.underline} などの実体面における要素も考慮している（最判昭和58年9月6日参照）。

## 証拠の関連性
### 前科証拠

* 関連性否定の趣旨（自然的関連性まで否定されるわけでない）
* 「前科に係る犯罪事実が顕著な特徴を有し、かつ、それが起訴に係る犯罪事実と相当程度類似する」場合には、前科証拠を被告人と犯人の同一性を証明するために用いることが許される。
    * 顕著な特徴を有する前科犯罪事実と同じ犯罪事実であるならば、悪性格の推認を介在させずに犯人性を推認できるから。
* 「行動傾向の固着化」や「強固な犯罪傾向」に対する考え方
    * 他に選択の余地がないほどに強固に習慣化しているか、被告人の性格の中に根付いているといえる程度があれば、前科証拠を利用できるとする立場を認めて良いか？
    * 被告人の犯罪性向を介した推認だとしても、推認力が相当程度に大きい場合には多少弊害があっても比較衡量したら満たされるというふうに考える余地も出てくるのではないか？というのが近時の有力説。
* 注意：「顕著な特徴」と「強固な犯罪傾向」の違い（基礎にある経験則）
    * 顕著な特徴：その人以外がやった可能性がない、その人しかできないというような手法である（第三者がやった可能性を排斥する方向の推認）
    * 強固な犯罪傾向：その人自身が特定の状況下において一定の行動に出る可能性が高いので本件犯行をやった可能性が高いという方向の推認
* ①被告人の犯罪性向といった実証的根拠に乏しい人格評価につながりやすく、そのために事実認定を誤らせるおそれがあること

    「過去の同種犯罪事実」→「被告人の犯罪性向・悪性格」→「本件犯罪における犯人性」という推認過程

    2個目の推認について、裁判官が被告人に対する安直な偏見を持って判断し、[推認力が過大評価されてしまう危険]{.underline} がある。
* ②当事者が前科の内容に立ち入った攻撃防御を行う必要が生じるなど、その [取り調べに付随して争点が拡散するおそれ]{.underline} がある。
* 同種事件が併合審理されている場合に、①②のいずれも妥当するのか？（金築裁判官の指摘）

### 科学的証拠

* 「科学的証拠」に対して過信し、証拠力を過大評価する恐れ
* DNA鑑定

    ①「科学的原理が理論的正確性を有し、具体的な実施の方法も、その技術を習得した者により、科学的に信頼される方法で行われた」（抽象的な信頼性）

    ②本件事案における具体的な実施方法の適切性
* 犬の臭気選別試験

    [{{< fa arrow-right >}}]{.color-minty} 以下から証拠能力を認めた（科学的原理の理論的正確性は未だ不明確・解明されてもいないので専門化した経験則を噛ませている）。
    * 専門的な知識・経験を有する指導手が行ったこと
    * 臭気選別能力が優れ、選別時において体調等も良好でその能力がよく保持されている警察犬を使用して実施したこと
    * 臭気の採取、保管の過程、臭気選別方法に不適切な点がないこと

## 自白の証拠能力

* 不任意自白の排除を要求する趣旨
    * 人権擁護説：意思決定の自由や黙秘権を侵害したら自白の任意性が疑われるという考え方
    
    （→約束による自白を捕捉できない）
    * 虚偽排除説：[強い利益誘導の下でなされた自白]{.underline} は、一般的類型的に虚偽である疑いが高まるので証拠能力が否定されるという考え方
    
    [{{< fa arrow-right >}}]{.color-minty} 供述状況に着目して一般的類型的に虚偽自白が誘発されやすい状況かどうかを判断する
    * 違法排除説：手続の適正の確保（司法の廉潔性、将来違法捜査の抑止）の観点から自白が排除されるという考え方
* [利益の提供主体と提示された具体的利益]{.underline} の両方を見る。
* 派生証拠（違法収集証拠排除法則の適用）
    * 虚偽排除説から根拠づけようとすると難しい面。
    * 違法収集証拠排除法則は、供述証拠に対しても適用されるから、手続の違法が重大であり、これを証拠とすることが違法捜査抑止の見地から相当でない場合には、証拠能力を否定する。
    * ただし、物的証拠に対する違法収集証拠排除法則の基準との関係性はなお問題。
* 問題の処理
    * 現在は自白に対しては自白法則と違法収集証拠排除法則の両方が適用されるとする考え方が支配的で、その上で実務では一般的に二元説といった考え方が取られる。
    * まず [自白法則は虚偽排除と人権擁護だけで説明する（任意性説）]{.underline} 。これに対して、手続の違法問題は全部、違法収集証拠排除法則で考える。このように、ある種自白法則と違法収集排除法則の根拠を完全に住み分けてしまう見解というのが実務では支配的である。

## 伝聞証拠

* 伝聞証拠排除の趣旨（伝聞と非伝聞）
    * 供述者の **知覚、記憶、叙述** という過程を経て供述されるところ、誤りが介在する恐れ
    * 公判廷において、宣誓、反対尋問、裁判官による供述態度の観察によって誤りを排除することができない
* 要証事実（当該証拠によって直接証明しようとする事実）が何か？
    * 要証事実との関係で、**供述内容の真実性** を立証しようとする場合には、伝聞証拠となる。
    * 精神状態に対する供述が伝聞証拠に当たらない理由
        * 内心の事情は、**知覚・記憶の過程** が欠如しているため、非伝聞と評価されるのが通説（表現の真摯性・叙述に誤りが入る可能性については、公判廷で確認できる）。
        * 伝聞証拠だとしてしまうと、本人の供述が最高の証拠で何としても採用したいとする場合には324条の準用する321条1項3号になる。あまりに重すぎ。
        * 非供述的用法の場合には、発言をしたこと自体が要証事実になる（謀議の場合など）。この場合にも、真摯性が問題になる（非伝聞証拠でも関連性が問題になる）。
    * 犯行計画メモ：犯行の意思・計画を要証事実とした場合には、知覚・記憶の部分が欠落している犯行計画メモについては、その作成が真摯になされたことが証明されれば、その信用性をテストする必要はない。
    * 謀議参加者の1人が合意された結果を書き留めた書面
        * 共謀加担者の意図・計画は独立して存在するので、全員の心理状態が記述されていると見るには状況を限定する必要がある。
        * 最低限記述者の意図しか示していない。しかし、その場にいた全員の意思が合致していることを別途立証できれば証拠として利用できるのでは（署名など）。
        * 共同意思形成をする上で用いられた手段を構成する証拠物としての利用
* 検察官の立証事項を維持すると伝聞証拠に当たり原則として証明能力が求められないことになる場合には、[対象証拠それ自体から直接抽き出しうる限度に立証事項を裁判所が減縮することができる]{.underline} としている。
    * 一次的には検察官の立証趣旨を尊重し（⇦当事者主義）、そのままだと証拠能力が認められなくなってしまうという場合に、二次的に立証事項が変更される。
    * 検察官が主張する要証事実であると、およそ推認過程が経験則で成り立たないという場合には自然的関連性が否定されるので、裁判所が適切な要証事実を設定する必要がある。

### 伝聞例外

* 検察官調書（321条1項2号）
    * 「公判期日において供述することができない」
    
        [{{< fa arrow-right >}}]{.color-minty} 「検察官面前調書が作成され証拠請求されるに至った事情や、供者が国外にいることになった事由のいかんによっては」 検察官面前調書の証拠能力が否定されるべき場合がありうる。

    * 手続的正義の観点から公正さを欠く場合（∵憲法37条2項が証人審問権を保障している）
    * 被告人側の不利益：証人審問権、手続上の不公正
    
        対立利益：真実の発見、事案の真相解明
    
        [{{< fa arrow-right >}}]{.color-minty} この比較衡量によって判断するのだから、退去強制の一事だけで決まるものではない
    * 全面的供述拒否と一部記憶喪失（前段と後段）
        * 相反性が認められる場合には2つある
        
            [{{< fa arrow-right >}}]{.color-minty} 他の証拠と相まって要証事実につき異なる認定を生ずる蓋然性がある場合
        
            [{{< fa arrow-right >}}]{.color-minty} 公判期日の証言によっては具体的な心証形成ができない場合
    * 特信性：基本的には外部的付随事情（取調べ状況、公判の状況等）を考慮する。ただし、内容も外部的付随事情を推認させるために考慮要素として使うことはできる。
        * 客観的事実への合致は証明力判断であるから、証拠能力の判断段階で考慮すべきではない（現行法の立て付けに合わない）。
* 検証調書・鑑定書（321条3項）
    * 実況見分調書にも同項の適用がある。
* 弾劾証拠（328条）※非伝聞証拠の確認規定
    * 「公判準備または公判期日における被告人、証人その他の者の供述が、別の機会にしたその者の供述と矛盾する場合に、[矛盾する供述をしたこと自体の立証を許すことにより公判準備または公判期日におけるその者の供述の信用性の減殺を図る]{.underline} ことを許容する趣旨」
    * 自己矛盾供述にのみ適用
    * 補助事実についても厳格な証明が必要なのか？
    
        [{{< fa arrow-right >}}]{.color-minty} 主要事実や間接事実の認定に直接重大な影響を及ぼす重要な証拠であるため、自由な証明では足りないと考えるのは一つの方法だが、従来は **自由な証明で足りる** と考えられてきた（実務家はこれを維持したい）。
    * 増強証拠の可否 [{{< fa arrow-right >}}]{.color-minty} 不可
    
        $\because$ 経験則上 [要証事実を立証することに使えないので関連性が否定される]{.underline} 上、仮に、捜査段階で言っていた供述内容が信用できるから、同じ内容の公判証言も信用できるのだというロジックを取ろうとすると、それは公判外の供述内容の真実性の話になので、伝聞法則の潜脱だから許されない。
* 写真、録音テープ、ビデオ
    * 関連性（ある証拠から [最終的な立証命題までを経験則に従って推認していくことができるか]{.underline} と、[最終的な立証命題が本件の訴訟の結論に影響するか]{.underline} の2つのレベルがありうる）
    * 検証調書等に添付される写真：検証調書等の説明的供述部分を補完する趣旨のもので、検証調書に添付された写真は検証調書に記載された供述の一部として取り込まれているから、供述調書として扱われる。
        * 添付写真の事件との関連性は、説明部分の証拠能力があることによって初めて基礎付けられるから、検証調書の他の叙述の証拠能力に従う。
* 再現実況見分調書（いわゆる現場指示と現場供述の違い）
    * 立会人の指示説明は実況見分の一つの手段に止まるにすぎないので、結局実況見分の結果を記載するのに他ならない。あくまで手がかりであって実況見分の動機を基礎付けるものにすぎない。
    
        e.g., 「ここで轢きました」 [{{< fa arrow-right >}}]{.color-minty} ブレーキ痕発見 [{{< fa arrow-right >}}]{.color-minty} 実況見分調書へ記録（なぜブレーキ痕を検証したかを示すために被告人の供述を記載する）

## 違法収集証拠

* 適正手続の保障・司法の廉潔性・将来の違法捜査の抑止

    [{{< fa arrow-right >}}]{.color-minty} 違法収集証拠排除法則
    * 適正手続の要請（憲法35条、31条）を直接の根拠とするのではなく、その趣旨を考慮している。
    * 違法収集証拠の証拠能力はあくまで刑訴法の解釈に委ねられている。
* 考慮要素：**①手続違反の程度、②手続違反のなされた状況、③手続違反の有意性（捜査機関の意図）、④手続違反の頻発性、⑤事件の重大性**
    * 強制捜査であると違法かどうかとその程度を区別する実益が出てくる。
* 「①令状主義の精神を没却するような重大な違法があり（違法の重大性）

    ⏪司法の廉潔性維持：軽微な違法のある証拠についてもどんどん排除するような司法を国民は信頼してくれないが、一方で重大な違法のある証拠について採用すればこれまた国民の信頼を害する（違法の重大性によって司法の廉潔性が傷つけられる程度が違う　※利益衡量の臨界点

    ②これを証拠として許容することが、将来における違法な捜査の抑制の見地からして相当でない（排除相当性）と認められる場合」

    ⏪将来の違法捜査の抑止と真相解明の必要性との比較衡量

* ①違法性の承継
    * [一連の違法な手続によりもたらされた状態を直接利用してなされる手続]{.underline} は違法性を承継する。
    * 違法収集証拠排除法則の2要件は、後続の手続に適用される。
    * 違法行為と証拠との間に厳密な因果関係を必要とするわけではない。とはいえ、時間的な先後関係のみで限界づけるわけでもない。
* ②毒樹の果実論
    * 理由：①違法収集証拠排除法則の骨抜きを防ぐ②捜査というものが連続した繋がりをもつ手続きである以上、その範囲が広汎になりすぎる恐れ
    * 考慮要素（通説）：第一次証拠の獲得手続の違法の程度、第一次証拠と派生証拠との関連性の程度、証拠の重要性、事案の重大性
* ③川出説
    * [違法な手続と証拠との（密接な）関連性]{.underline} を問題にする。
    * 違法収集証拠排除法則の2要件は先行する手続に適用される。
    * 相互排他的な基準ではない。
* ④強制処分が介在する場合には、違法収集証拠1による令状発布が違法となって捜索bが違法になる。

## 裁判
### 概括的認定・択一的認定

* 同一構成要件内：「罪となるべき事実」の特定がなされればよい（訴因の特定の問題と共通）。
* 異なる構成要件にまたがる場合
    * 問題
    
        ①利益原則違反：それぞれについて合理的な疑いを挟まない程度の証明がないにもかかわらず、「AまたはB」の関係にして処罰することは利益原則に反する。
    
        ②罪刑法定主義違反：2つの犯罪を1つの罪名として考えることになり、新たな構成要件（合成的構成要件）を作り出してしまう
    * 同意殺人と殺人、死体遺棄と保護責任者遺棄（論理的な択一関係にある場合には、軽い方の罪を認定して良いのか？）
* ①証明の単位を超えるような択一的認定
    * 利益原則との関係：実務家の間では重い罪に利益原則を適用して事実を擬制すれば、軽い罪で有罪認定できるという風な考え方が有力な一方、学説は一般にこういう事実擬制に批判的であって、大澤先生を中心に利益原則は事実の擬制をもたらすものではないのであって、むしろ刑法解釈を捉え直すべきだという主張をなされる。
    * 罪刑法定主義との関係：罪刑法定主義が国民への処罰範囲の告知のみなのであれば、異なる構成要件間で択一的認定をしても罪刑法定主義には反しないという風な結論が出てくるが、それに留まらずに法定主義というところに重みをもたせて、立法府が構成要件ごとに刑罰権を設定するというところまで含むのだと考えると、異なる構成要件間で択一的認定をするというのは、裁判所が勝手に構成要件を作ることになるので、やはり罪刑法定主義違反となる。
* ②証明の単位内の択一的認定（堂々と択一的認定を行って良い）
* 証明の単位：利益原則の適用単位が構成要件（多数説）　or 訴因（川出先生）。

### 一事不再理効

* 有罪判決の内容的確定力：有罪判決が示された犯罪自体に及ぶ
* 一事不再理効：検察官が設定する訴因に基づいて判断される。公訴事実の同一性のある範囲で訴因変更というのが認められて、その範囲であれば審理される危険というのはあるから、[公訴事実の同一性の範囲で一事不再理効の効力が及ぶかどうか]{.underline} を判断すべき。
    * 根拠：憲法39条の二重の危険の解釈
    * 有罪判決の内容的確定力が及ぶ範囲と公訴事実の同一性の範囲で一事不再理効が及ぶ範囲がずれる。
    * 両訴因の処罰をしようとする場合→公訴事実の単一性（牽連犯で一罪と評価されるので変更可能）
* 単純窃盗と常習窃盗
    * 前訴と後訴の公訴事実の同一性によって判断。それぞれの訴因のみを基準として比較対照することによって行う。
    
    ①検察官の訴因を尊重するべき（訴追裁量権）
    
    ②それぞれの行為の独立性も強いので、検察官がそれぞれに起訴することにも合理的な理由がある（常習特殊窃盗の性質）
    
    * ただし、一方の訴因が常習窃盗罪である場合には、[訴因自体において一方の単純窃盗罪が他方の常習窃盗罪と実体的に一罪を構成するかどうかにつき検討すべき契機が存在する]{.underline} として、単純窃盗罪が常習性の発露として行われたか否かについて付随的に心証形成する必要がある。
