---
title: "会社法［期末試験対策］"
date: 2/1/2024
categories: [会社法, 期末試験対策]
---

## 他人名義による株式の引き受け

実質上の引受人すなわち名義借用者がその株主となる

$\because$ 一般私法上の法律行為の場合と同じく、真に契約の当事者として申込をした者が引受人としての権利を取得し、義務を負担する

[{{< fa arrow-right >}}]{.color-minty} 通常は、経済的出捐をした者が契約の当事者と認定されるだろう。

## 株式の相続

* 株式の持分は、株主たる資格において会社に対して有する法律上の地位を意味する

相続人は被相続人の法律上の地位を包括的に承継するのであるから、持分の取得により株主たる地位をも当然に承継したといえる

* 権利行使者の指定（106条）がない限り、特段の事情がない限り、原告適格を有しない。持分の準共有者間において権利行使者を決めるに当たっては、持分の価格に従い、その過半数を持ってこれを決定する（民法252条）ことができる。
    * 106条の趣旨は、1人でも反対すれば全体の権利行使が不可能となると解すると会社の運営にも支障を来たす恐れがあることから、会社の事務処理上の便宜のため。
    * 民法264条の「特別の定め」
    * 議決権行使は、直ちに株式を処分し、又は株式の内容を変更することになるなどの特段の事情がない限り、株式の管理に関する行為に当たる。
* 権利行使者の通知なくして株主総会不存在訴訟を提起した場合
    
	会社の立場
    * 株主総会における決議の成立を主張・立証しなければならない
    * 手続きの欠缺を主張して原告適格を争う
    
	[{{< fa arrow-right >}}]{.color-minty} 規定の趣旨を同一訴訟手続内で恣意的に使い分けるものとして、訴訟上の防御権を濫用し、著しく信義則に反して許されない

## 株主平等原則（109条）

* 多数決の濫用や会社経営者による恣意的な権限行使から、個々の株主の利益を保護するため、会社は、株主をその有する株式の内容及び数に応じて平等に取り扱わなければならない。
* 正義・衡平の理念を基礎として全ての団体に共通する原則
    
    [{{< fa arrow-right >}}]{.color-minty} 属人的定めの制度（2項）にも株主平等原則の趣旨に及ぶ規制が及ぶ
    
    差別的取り扱いが合理的な理由に基づかず、その目的において正当性を欠いている場合

手段の必要性や相当性を欠くような場合
にはそのような定款変更は無効

## 譲渡制限株式

趣旨：専ら会社にとって好ましくない者が株主となることを防止し、持って譲渡人以外の株主の利益を保護する

非公開会社

会社の支配権に関わる持株比率の維持に係る既存株主の利益の保護が重視される

２．株式の発行

「不公正な発行価額」（公正発行価額）

上場会社が額面普通株式を株主以外の第三者に対して有利な資本調達を企図する場合

    * 本来：新株主に旧株主と同等の資本的寄与を求めるべき。発行価額は旧株の時価と等しくするべき。
    * But　新株を消化し資本調達の目的を達成するためには、原則として発行価額を時価よりも多少引き下げる必要がある。
    * 諸事情を考慮して、旧株主の利益と会社が有利な資本調達を実現するという利益との調和との中に求められる。

## 新株（＋予約権）の第三者割り当て

不公正発行の該当性

⓪前提の論理

取締役は株主の資本多数決によって選任される執行機関にすぎない

被選任者たる取締役に選任者たる株主構成の変更を主要な目的とする新株発行を一般的に許容することは、機関権限の分配を定めた法意に反する

[{{< fa arrow-right >}}]{.color-minty} 誰を経営者としてどのような事業構成の方針で会社を経営させるかは、株主総会における取締役選任を通じて株主が資本多数決によって決すべき

①主要目的ルール

1. 会社の支配権につき争いがあり
2. 現経営陣が、支配権を争う特定の株主の持株比率を低下させ、もって自らの支配権を維持・確保することなどを主要な目的としている

②例外：正当化事情

株主全体の利益の保護という観点から新株発行等を正当化する特段の事情

会社の企業価値が毀損され、会社の利益ひいては株主の共同の利益を害するような場合には、それを防止することが事情になる

敵対的買収に対する対抗手段として必要性や相当性が認められる限り、正当性が認められうる

３．株主総会

代理人資格を株主に制限する定款（有効性）

合理的な理由がある場合に、相当と認められる程度の制限を加えることは許される

趣旨：株主以外の第三者によって攪乱されることを防止し、会社の利益を保護する

## 利益供与

株主の権利行使に影響を及ぼす恐れのない正当な目的に基づき許与される場合で、

かつ、個々の株主に供与される額が社会通念上許容される範囲のもので、株主全体に供与される総額も会社の財産的基礎に影響を及ぼすものではない