---
title: "弘前データ４：フローラスキャンデータの探索"
author: "司馬博文"
date: 5/24/2025
number-sections: true
code-fold: true
bibliography: 
  - ../../assets/2023.bib
  - ../../assets/2024.bib
  - ../../assets/2025.bib
csl: ../../assets/apalike.csl
fig-align: center
abstract: |
  [`hirosaki2.qmd`](hirosaki2.qmd) では BP と LAB の関係のモデリング，
  [`hirosaki3.qmd`](hirosaki3.qmd) では $\Sigma$-FLC と LOX-1 の関係をモデリングした．
  ここではフローラスキャンデータの探索を行う．
format:
  html: 
    code-fold: false
    execute:
      cache: false
    fig-width: 10
    fig-height: 8
---

```{r}
library(readxl)
library(knitr)
df <- readRDS("df.rds")
kable(head(df))
```

## タイプの予測問題

### BP との関係の探索

```{r}
#| output: false
library(dplyr)
df$BP_level <- case_when(
  df$BP > 0.9 ~ 3,
  df$BP > 0.7 & df$BP <= 0.9 ~ 2,
  df$BP <= 0.7 ~ 1
)
```

```{r}
length(df[df$BP_level == 3, ]$BP)/dim(df)[1]
length(df[df$BP_level == 2, ]$BP)/dim(df)[1]
length(df[df$BP_level == 1, ]$BP)/dim(df)[1]
```

### タイプを予測できるか？

```r
library(brms)

formula_nominal <- bf(
  タイプ ~ 1 + BP,
  family = categorical(link = "logit")
)
nominal_type <- brm(
  formula_nominal,
  data = df,
  chains = 4, cores = 4, iter = 8000
)
saveRDS(nominal_type, "nominal_type.rds")
```

```{r}
#| echo: false
#| output: false
library(brms)
nominal_type <- readRDS("nominal_type.rds")
library(showtext)  # 日本語フォント用のパッケージ

# 日本語フォントの設定
font_add_google("Noto Sans JP", "notosans")  # Google Fontsからフォントを追加
showtext_auto()  # 自動的にshowtextを使用するように設定
```

```{r}
ce <- conditional_effects(nominal_type, effects = "BP", categorical = TRUE)

library(ggplot2)

# プロットに水平方向の直線を追加
plot(ce, plot = FALSE)[[1]] +
      theme(
    axis.text = element_text(size = 24),  # 軸の目盛りの文字サイズ
    axis.title = element_text(size = 30),   # 軸ラベルの文字サイズ
        legend.text = element_text(size = 36),  # 凡例のテキストサイズ
    legend.title = element_text(size = 24)  # 凡例のタイトルサイズ
  )

```

### FLC との関係の探索

```{r}
df_FLC <- df[is.na(df$`BP備考`), ]
df_FLC$FLC_level <- case_when(
  df_FLC$FLCΣ >= 2 ~ 3,
  df_FLC$FLCΣ >= 1.0 & df_FLC$FLCΣ < 2 ~ 2,
  df_FLC$FLCΣ < 1.0 ~ 1
)
length(df_FLC[df_FLC$FLC_level == 3, ]$FLCΣ)/dim(df_FLC)[1]
length(df_FLC[df_FLC$FLC_level == 2, ]$FLCΣ)/dim(df_FLC)[1]
length(df_FLC[df_FLC$FLC_level == 1, ]$FLCΣ)/dim(df_FLC)[1]
```

### FLC はタイプを予測できるか？


```r
library(brms)

formula_nominal <- bf(
  タイプ ~ 1 + FLCΣ,
  family = categorical(link = "logit")
)
nominal_type_FLC <- brm(
  formula_nominal,
  data = df_FLC,
  chains = 4, cores = 4, iter = 8000
)
saveRDS(nominal_type_FLC, "nominal_type_FLC.rds")
```

```{r}
#| echo: false
#| output: false
nominal_type_FLC <- readRDS("nominal_type_FLC.rds")
```

```{r}
ce <- conditional_effects(nominal_type_FLC, effects = "FLCΣ", categorical = TRUE)

# プロットに水平方向の直線を追加
plot(ce, plot = FALSE)[[1]] +
      theme(
    axis.text = element_text(size = 24),  # 軸の目盛りの文字サイズ
    axis.title = element_text(size = 30),   # 軸ラベルの文字サイズ
        legend.text = element_text(size = 36),  # 凡例のテキストサイズ
    legend.title = element_text(size = 24)  # 凡例のタイトルサイズ
  )

```

## 多様性の予測問題

### BP は多様性を予測できるか？

```r
library(brms)

formula_mult <- bf(
  多様性 ~ 1 + BP,
  family = cumulative(link = "logit")
)
mult_diversity_BP <- brm(
  formula_mult,
  data = df,
  chains = 4, cores = 4, iter = 8000
)
saveRDS(mult_diversity_BP, "mult_diversity_BP.rds")
```

```{r}
#| echo: false
#| output: false
mult_diversity_BP <- readRDS("mult_diversity_BP.rds")
```

```{r}
ce <- conditional_effects(mult_diversity_BP, effects = "BP", categorical = TRUE)

# プロットに水平方向の直線を追加
plot(ce, plot = FALSE)[[1]] +
      theme(
    axis.text = element_text(size = 24),  # 軸の目盛りの文字サイズ
    axis.title = element_text(size = 30),   # 軸ラベルの文字サイズ
        legend.text = element_text(size = 36),  # 凡例のテキストサイズ
    legend.title = element_text(size = 24)  # 凡例のタイトルサイズ
)
```

### FLC は多様性を予測できるか？

```r
formula_mult <- bf(
  多様性 ~ 1 + FLCΣ,
  family = cumulative(link = "logit")
)
mult_diversity_FLC <- brm(
  formula_mult,
  data = df_FLC,
  chains = 4, cores = 4, iter = 8000
)
saveRDS(mult_diversity_FLC, "mult_diversity_FLC.rds")
```

```{r}
#| echo: false
#| output: false
mult_diversity_FLC <- readRDS("mult_diversity_FLC.rds")
```

```{r}
ce <- conditional_effects(mult_diversity_FLC, effects = "FLCΣ", categorical = TRUE)

# プロットに水平方向の直線を追加
plot(ce, plot = FALSE)[[1]] +
      theme(
    axis.text = element_text(size = 24),  # 軸の目盛りの文字サイズ
    axis.title = element_text(size = 30),   # 軸ラベルの文字サイズ
        legend.text = element_text(size = 36),  # 凡例のテキストサイズ
    legend.title = element_text(size = 24)  # 凡例のタイトルサイズ
)
```