---
title: "弘前データ４：フローラスキャンデータの探索"
author: "司馬博文"
date: 5/24/2025
number-sections: true
code-fold: true
bibliography: 
  - ../../assets/2023.bib
  - ../../assets/2024.bib
  - ../../assets/2025.bib
csl: ../../assets/apalike.csl
fig-align: center
abstract: |
  [`hirosaki2.qmd`](hirosaki2.qmd) では BP と LAB の関係のモデリング，
  [`hirosaki3.qmd`](hirosaki3.qmd) では $\Sigma$-FLC と LOX-1 の関係をモデリングした．
  ここではフローラスキャンデータの探索を行う．
format:
  html: 
    code-fold: false
    execute:
      cache: false
    fig-width: 10
    fig-height: 8
---

```{r}
library(readxl)
library(knitr)
df <- readRDS("df.rds")
df <- df[is.na(df$`BP備考`), ]
kable(head(df))
```

```{r}
df_IRT_long <- readRDS("df_IRT_long.rds")
df_IRT_long <- df_IRT_long[df_IRT_long$FLCΣ > 0, ]
kable(head(df_IRT_long))
```

## BP との関係

D は合計 $6$ 人しかいない．

```{r}
df <- subset(df, type != "D" & !is.na(diversity))
df$type <- droplevels(df$type)
```

### 視覚化

```{r}
library(ggplot2)

ggplot(df, aes(x = type, fill = diversity)) +
    geom_bar(position = "fill") +
    geom_text(data = df, aes(label = ..count..), stat = "count", position = position_fill(vjust = 0.5)) +
  theme_minimal() +
  labs(title = "タイプ別の多様性の分布",
       x = "タイプ",
       y = "割合") +
  theme(text = element_text(family = "HiraKakuPro-W3"),
        plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values = c(
    "1" = "#9999FF",    # 薄い青
    "2" = "#99FF99",  # 薄い緑
    "3" = "#FF9999"     # 薄い赤
  ))
```

```{r}
library(ggplot2)

ggplot(df, aes(x = type)) +
  geom_histogram(stat = "count", fill = "skyblue", color = "black") +
  theme_minimal() +
  labs(title = "タイプのヒストグラム",
       x = "タイプ",
       y = "頻度") +
  theme(text = element_text(family = "HiraKakuPro-W3"),
        plot.title = element_text(hjust = 0.5))
```

* 明らかに type A は diversity 1 が少ない．

### 散布図

```{r}
ggplot(df, aes(x = BP, y = diversity, color = type)) +
  geom_point() +
  labs(title = "BPとDiversityの散布図", x = "BP", y = "Diversity", color = "Type") +
  theme_minimal() +
  xlim(0, 2.5)
```

```{r}
ggplot(df, aes(x = BP, y = FLCΣ, color = type)) +
  geom_point() +
  labs(title = "BPとFLCΣの散布図", x = "BP", y = "FLCΣ", color = "Type") +
  theme_minimal()
```

```{r}
ggplot(df, aes(x = BP, y = FLCΣ, color = diversity)) +
  geom_point() +
  labs(title = "BPとFLCΣの散布図", x = "BP", y = "FLCΣ", color = "Type") +
  theme_minimal()
```

### BP の予測：全部切片にしてみる

```r
library(brms)
bf <- bf(
  BP ~ 1 + (1|type:diversity)
)

fit_BP <- brm(
  formula = bf,
  data = df,
  family = gaussian(),
  iter = 8000, chains = 4, cores = 4)
```

```{r}
#| output: false
#| echo: false
library(brms)
fit_BP <- readRDS("./4-1/fit_BP.rds")
```

```{r}
ranef(fit_BP)$`type:diversity`
```

```{r}
ranef <- ranef(fit_BP)$`type:diversity`
posterior_means <- ranef[,1,"Intercept"]
lower_bounds <- ranef[,3,"Intercept"]
upper_bounds <- ranef[,4,"Intercept"]
plot_df <- data.frame(
  type = rownames(ranef),
  mean = posterior_means,
  lower = lower_bounds,
  upper = upper_bounds
)
p <- ggplot(plot_df, aes(x = mean, y = type)) +
  geom_point() +
  geom_errorbar(aes(xmin = lower, xmax = upper), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = NULL,
       x = "Posterior Estimate",
       y = NULL)
p
```

### BP の予測：多様性，ただしタイプごと

```r
library(brms)
bf <- bf(
  BP ~ (type|diversity)
)

fit_BP_diversity <- brm(
  formula = bf,
  data = df,
  family = gaussian(),
  iter = 8000, chains = 4, cores = 4)
```

```{r}
#| output: false
#| echo: false
library(brms)
fit_BP_diversity <- readRDS("./4-1/fit_BP_diversity.rds")
```

```{r}
ranef(fit_BP_diversity)$diversity
```

```{r}
ranef <- ranef(fit_BP_diversity)$diversity
posterior_means <- ranef[,1,"Intercept"]
lower_bounds <- ranef[,3,"Intercept"]
upper_bounds <- ranef[,4,"Intercept"]
plot_df <- data.frame(
  diversity = rownames(ranef),
  mean = posterior_means,
  lower = lower_bounds,
  upper = upper_bounds
)
p <- ggplot(plot_df, aes(x = mean, y = diversity)) +
  geom_point() +
  geom_errorbar(aes(xmin = lower, xmax = upper), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = NULL,
       x = "Posterior Estimate",
       y = NULL)
p
```

## 個人の応答を予測できたら面白い

### 個人係数の予測

```{r}
#| output: false
library(brms)
fit_1PL_cov <- readRDS("../../../Desktop/Mentalism/3-BayesianDataAnalysis/Cocosiru/rdb/fit_1PL_cov.rds")
```

```{r}
ran_id_list <- ranef(fit_1PL_cov)$id[,1,]

df_IRT_long$ran_id <- ran_id_list[match(df_IRT_long$id, names(ran_id_list))]

df_IRT_long <- df_IRT_long[!is.na(df_IRT_long$ran_id), ]

summary(df_IRT_long$ran_id)
```

```r
library(brms)
bf <- bf(
  ran_id ~ 1 + (1|type)
)

fit_ranid <- brm(
  formula = bf,
  data = df_IRT_long,
  family = gaussian(),
  iter = 8000, chains = 4, cores = 4)
```

```{r}
#| output: false
#| echo: false
library(brms)
fit_ranid <- readRDS("./4-1/fit_ranid.rds")
```

```{r}
library(ggplot2)
ranef <- ranef(fit_ranid)$type
posterior_means <- ranef[,1,"Intercept"]
lower_bounds <- ranef[,3,"Intercept"]
upper_bounds <- ranef[,4,"Intercept"]
plot_df <- data.frame(
  type = rownames(ranef),
  mean = posterior_means,
  lower = lower_bounds,
  upper = upper_bounds
)
p <- ggplot(plot_df, aes(x = mean, y = type)) +
  geom_point() +
  geom_errorbar(aes(xmin = lower, xmax = upper), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = NULL,
       x = "Posterior Estimate",
       y = NULL)
p
```

### タイプごとの係数の予測

大変重くて実行が難しい．

```r
formula_1PL_cov <- bf(
  res ~ 1 + (1|item) + (BP|type) + FLCΣ
)
fit_1PL_cov_type <- brm(
  formula = formula_1PL_cov,
  data = df_IRT_long,
  family = brmsfamily("bernoulli", link = "logit"),
  iter = 8000, chains = 4, cores = 4
)
```

```{r}
#| echo: false
fit_1PL_cov_type <- readRDS("./4-1/fit_1PL_cov_type.rds")
```

```{r}
conditional_effects(fit_1PL_cov_type , effects = "FLCΣ")
```

```{r}
ranefs <- ranef(fit_1PL_cov_type)$type
posterior_means <- ranefs[,1,"BP"]
lower_bounds <- ranefs[,3,"BP"]
upper_bounds <- ranefs[,4,"BP"]
plot_df <- data.frame(
  type = rownames(ranefs),
  mean = posterior_means,
  lower = lower_bounds,
  upper = upper_bounds
)

p <- ggplot(plot_df, aes(x = mean, y = type)) +
  geom_point() +
  geom_errorbar(aes(xmin = lower, xmax = upper), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = NULL,
       x = "Posterior Estimate",
       y = "Type") +
  theme(
    axis.text = element_text(size = 24),  # 軸の目盛りの文字サイズ
    axis.title = element_text(size = 30),   # 軸ラベルの文字サイズ
    legend.text = element_text(size = 36),  # 凡例のテキストサイズ
    legend.title = element_text(size = 24),  # 凡例のタイトルサイズ
    plot.margin = margin(r = 20, l = 10)  # 右側の余白を50ポイントに設定
  )
p
```

### 応答曲線は！？

```{r}
#| output: false
ran_ef_list <- ranef(fit_1PL_cov_type)$item[,1,]
ran_coef0_list <- ranef(fit_1PL_cov_type)$type[,1,"Intercept"]
ran_coef1_list <- ranef(fit_1PL_cov_type)$type[,1,"BP"]

a <- -1.62
b <- -0.09

df_IRT_long$ran_ef <- ran_ef_list[match(df_IRT_long$item, names(ran_ef_list))]
df_IRT_long$ran_coef0 <- ran_coef0_list[match(df_IRT_long$type, names(ran_coef0_list))]
df_IRT_long$ran_coef1 <- ran_coef1_list[match(df_IRT_long$type, names(ran_coef1_list))]

df_IRT_long$pred_prob <- plogis(a + df_IRT_long$ran_ef + df_IRT_long$ran_coef0 + df_IRT_long$ran_coef1 * df_IRT_long$BP + b * df_IRT_long$FLCΣ)
library(pROC)
roc_obj <- roc(df_IRT_long$res, df_IRT_long$pred_prob)
```

```{r}
plot(roc_obj)
roc_obj$auc
```

### くそ，もっと AUC 上がらないのか？

```r
formula_type2 <- bf(
  res ~ 1 + (1|item) + (BP+FLCΣ|type)
)
fit_type2 <- brm(
  formula = formula_type2,
  data = df_IRT_long,
  family = brmsfamily("bernoulli", link = "logit"),
  iter = 8000, chains = 4, cores = 4
)
```

```{r}
#| echo: false
fit_type2 <- readRDS("./4-1/fit_type2.rds")
```

```{r}
ranefs <- ranef(fit_type2)$type
posterior_means <- ranefs[,1,"BP"]
lower_bounds <- ranefs[,3,"BP"]
upper_bounds <- ranefs[,4,"BP"]
plot_df <- data.frame(
  type = rownames(ranefs),
  mean = posterior_means,
  lower = lower_bounds,
  upper = upper_bounds
)

p <- ggplot(plot_df, aes(x = mean, y = type)) +
  geom_point() +
  geom_errorbar(aes(xmin = lower, xmax = upper), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = NULL,
       x = "Posterior Estimate",
       y = "Type") +
  theme(
    axis.text = element_text(size = 24),  # 軸の目盛りの文字サイズ
    axis.title = element_text(size = 30),   # 軸ラベルの文字サイズ
    legend.text = element_text(size = 36),  # 凡例のテキストサイズ
    legend.title = element_text(size = 24),  # 凡例のタイトルサイズ
    plot.margin = margin(r = 20, l = 10)  # 右側の余白を50ポイントに設定
  )
p
```

```{r}
ranefs <- ranef(fit_type2)$type
posterior_means <- ranefs[,1,"FLCΣ"]
lower_bounds <- ranefs[,3,"FLCΣ"]
upper_bounds <- ranefs[,4,"FLCΣ"]
plot_df <- data.frame(
  type = rownames(ranefs),
  mean = posterior_means,
  lower = lower_bounds,
  upper = upper_bounds
)

p <- ggplot(plot_df, aes(x = mean, y = type)) +
  geom_point() +
  geom_errorbar(aes(xmin = lower, xmax = upper), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = NULL,
       x = "Posterior Estimate",
       y = "Type") +
  theme(
    axis.text = element_text(size = 24),  # 軸の目盛りの文字サイズ
    axis.title = element_text(size = 30),   # 軸ラベルの文字サイズ
    legend.text = element_text(size = 36),  # 凡例のテキストサイズ
    legend.title = element_text(size = 24),  # 凡例のタイトルサイズ
    plot.margin = margin(r = 20, l = 10)  # 右側の余白を50ポイントに設定
  )
p
```

### 応答曲線上がれ！

```{r}
#| output: false
ran_ef_list <- ranef(fit_type2)$item[,1,]
ran_coef0_list <- ranef(fit_type2)$type[,1,"Intercept"]
ran_coef1_list <- ranef(fit_type2)$type[,1,"BP"]
ran_coef2_list <- ranef(fit_type2)$type[,1,"FLCΣ"]

a <- -1.62

df_IRT_long$ran_ef <- ran_ef_list[match(df_IRT_long$item, names(ran_ef_list))]
df_IRT_long$ran_coef0 <- ran_coef0_list[match(df_IRT_long$type, names(ran_coef0_list))]
df_IRT_long$ran_coef1 <- ran_coef1_list[match(df_IRT_long$type, names(ran_coef1_list))]
df_IRT_long$ran_coef2 <- ran_coef2_list[match(df_IRT_long$type, names(ran_coef2_list))]

df_IRT_long$pred_prob <- plogis(a + df_IRT_long$ran_ef + df_IRT_long$ran_coef0 + df_IRT_long$ran_coef1 * df_IRT_long$BP + df_IRT_long$ran_coef2 * df_IRT_long$FLCΣ)
library(pROC)
roc_obj <- roc(df_IRT_long$res, df_IRT_long$pred_prob)
```

```{r}
plot(roc_obj)
roc_obj$auc
```

いや，上がることは上がるんだよな……．