---
title: "ココシルデータ解析０"
subtitle: "概観：背景情報とミーティングの記録"
author: "司馬博文"
date: 2/26/2025
date-modified: 4/30/2025
number-sections: true
code-fold: true
bibliography: 
  - ../../assets/2023.bib
  - ../../assets/2024.bib
  - ../../assets/2025.bib
csl: ../../assets/apalike.csl
execute: 
  cache: false
fig-align: center
format:
  html: 
    code-fold: false
    execute:
      cache: true
# listing:
#   - id: cocosiru1-listing
#     type: grid
#     sort: false
#     contents:
#       - "source1.qmd"
#     page-size: 3
#     image-height: 100%
#     grid-columns: 1
#   - id: cocosiru2-listing
#     type: grid
#     sort: false
#     contents:
#       - "source2.qmd"
#     page-size: 3
#     image-height: 100%
#     grid-columns: 1
---

## ブリーフィング

株式会社プリメディカ ([HP](https://www.premedica.co.jp/) / [Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AA%E3%83%A1%E3%83%87%E3%82%A3%E3%82%AB)) は新たにバイオピリン測定サービス「[ココシル](https://cocoshiru.com/)」を2024年４月にスタートさせた．このサービスは尿中のバイオピリン濃度^[バイオピリンは体内のビリルビンが，活性酸素と結びつくことで生じる物質であり，体内の活性酸素の量の指標になる．極めて迅速に代謝され尿中に出るので，（ほとんど）リアルタイムな体内ストレスのモニタリングが可能として注目されている．@sec-appendix も参照．] を測定し，その濃度を100点満点にリスケーリングした「ココシルスコア」を報告する．

当社はすでに，LABとLOX-1の血中濃度測定による動脈硬化リスク評価サービス「[LOX-index](https://lox-index.com/)」と，便から腸内フローラの多様性を測定するサービス「[フローラスキャン](https://flora-scan.jp/)」との２つのサービスを提供している．

本新サービス「ココシル」は働く人のメンタルヘルスに焦点を合わせており，既存２サービスと併せて，多角的な予防医療サービスを提供することで顧客の囲い込みを目指している．

### 解析目的

本案件では，大きく分けて次の３つの目的がある．

#### 目的１：バイオピリンと離職イベントの依存構造の検討

究極的には，[休職・離職イベントの関連]{.underline}を解析することが目標である．

ただし，休職・離職のデータは得にくいため，「昇進・異動」というエンドイベントと，バイオピリンという絶対的な説明変数の間を媒介する変数を特定したり，個人ごとの変動効果も考慮した項目反応モデルを用いるなどの方法を模索することが基本的な方向性になる．

#### 目的２：バイオピリンと法定診断との相関の検討

2015年以降，労働安全衛生法に基づいて「[職業性ストレスチェック](https://www.mhlw.go.jp/bunya/roudoukijun/anzeneisei12/index.html)」が常時50人以上の事業場にて毎年の実施が義務付けられている．

従って多くの企業では，この法定義務である「職業性ストレスチェック」の結果とココシルスコアの結果を総合して，従業員のメンタルヘルスの評価に役立てたいという需要がある．

「職業性ストレスチェック」の結果とココシルスコアの結果との相関や深い関係性の解明が第一の目標．加えて，そのような独自知見があったならば，より多くの企業に「ココシル」サービスを導入してもらえることになり，マーケティングに大きく助力できる．

#### 目的３：バイオピリンと，LOX-indexとフローラスキャンとの関係の検討

ココシルスコアと，２つの既存サービスであるLOX-indexとフローラスキャンとの関係を検討する．

「ココシルスコアだけでなく，LOX-indexやフローラスキャンの結果もあれば，自身の健康状態についてより多くのことが知れる」というサービスを提供できれば，複数のサービス間で強いシナジー効果が生じ，囲い込み効果が強くなることが期待できる．

例えば，LOX-index では LDL などの脂質が酸化して得られる LAB の血中濃度が測定されるが，中高年では脂質を抑える薬を飲んでいる人の割合が多く，LAB の値が低く出てしまう一方で，バイオピリンは服薬に左右されない酸化ストレスの指標を与える．

服薬の存在により，LAB とバイオピリンと動脈硬化・精神疾患などのエンドイベントとの関係がどう変わるか？も重要な研究対象になる．

### データ

使用可能なデータは３種類ある．

1. 弘前データ

    2024 年度に弘前大学により，いわき市にて実施された健康診断の $N=1162$ の大規模データである．全被験者はプリメディカ社が提供する３サービスの測定結果が報告されていると同時に，職業性ストレスチェックのグループ B 29 項目への回答結果もあり，これらのデータを用いて，バイオピリンと職業性ストレスチェックとの関係を検討することができる．

2. プリメディカでのココシル検査データ

    プリメディカ社員 43 名を対象に実施された検査の結果があるが，関連する労務情報（勤務時間や昇進の有無）がないため，データの用途が定まっていない．

3. 一般企業でのココシル検査データ

    ある企業では，従業員 28 名を対象に，７月と10月の２回，繰り返しココシルスコアが測定された．同時に本企業では４月と10月に異動と昇進があり，その有無も紐づけられている．解析の結果，昇格がココシルスコアに正の影響を与える可能性が示唆されたが，28 名のデータではサイズが小さく，有意性は確認できなかった．

    また初回の測定は昇進の辞令発令後３ヶ月であるのに対し，２回目の測定は辞令があった当月である．
    この違いを考慮した項目反応モデルで解析したい．

## 現在までの研究結果の概要

### ココシルスコアと昇進との関係

- 7月と10月での２回測定データでは，随時尿にしたからなのか，とんでもない変化率が３ヶ月で出た．
  - 「３ヶ月でそんな変わるか？」というのが最初の疑問．
  - 10月に組織変更があった．顧客変更・部署異動の回帰係数は意味のある値を示さなかったが，昇進の回帰係数は何か反応があるようだった．

たかだか 28 名のデータで２回の繰り返し測定しかしておらず，10 月に昇進のあったものがうち 12 名だが４月に昇進したものは居なかったという不均衡性もあり，全く意味のある結論は出なかった．

<!-- ::: {#cocosiru1-listing}
::: -->

### 職業性ストレスチェックとの関係 {#sec-stress-check}

第２回 (2/27/2025) ミーティングでは次のアジェンダが設定された：

- 職業性ストレスチェックは産業界で一大サービスであり，それとの関連から説明したい．
- 「職業性ストレスチェックのどのような意味での要約になっているか？」を知りたい．
- [弘前の大規模データで検証したい]{.color-united}．

しかし職業性ストレスチェックの結果は，問診による回答でそもそも信頼性が低い上に，問診表としても本当に解像度が低く，
「イライラ感」「疲労感」「抑うつ感」「不安感」などの項目で５段階でのストレススコアが出るが，バイオピリン濃度との関係は希薄だった．

しかし唯一，「疲労感」「抑うつ感」「不安感」の項目で，最大値であるストレス５と回答した者（と言っても全体の 2~3% 程度）には，極めて低いバイオピリン値（0.5以下，通常0.5~1.0の間に入る）の者がほとんど居ない，という傾向が判明したのみであった．

* バイオピリン値で層別し，ストレスチェックという項目応答に対する項目反応モデルを推定し，そのパラメータの違いを見る，という方法はあり得るが，どう実務に活かせるか？
* 「バイオピリン値が平均より高かった者（例えば 1.0 以上）」のみを抜き出した部分標本を取り，そこで極値分布を用いたモデリングをし，違いが出るかどうかを見る？

<!-- ::: {#cocosiru2-listing}
::: -->

### 他サービスとの関連

* バイオピリン値と LAB の値は関係があるようだった．
  * しかし，バイオピリンを被説明変数，LAB を説明変数とし，年代ごとの LAB の変動効果をベイズ階層モデルを用いて推定した．
  * その結果，年齢が上がるごとに回帰係数は下がっていく関係が見られた．20~30 代と 50~60 代では LAB の変動効果が大きく異なり，符号を跨ぐほどであった．
  * これは服薬による交絡であることが疑われる．脂質 (LDL など) を抑える薬を飲んでいる者は，背景にある活性酸素量に依らずに LAB 値が低く出るが，バイオピリンは変わらず高い値を示す，ということが起こるためである．
  * 一方で少なくとも 20 代や 30 代で正の係数が推定されたことは想定通りであった．
* FCL 値と LOX-1 の値も同様に関係があることが期待され，次の解析目標である．

## 背景 {#sec-appendix}

### ビリルビンとバイオピリン

ビリルビンが活性酵素を除去しようとする中で，その残滓であるバイオピリンが活性酸素上昇／酸化ストレスのマーカーになることが知られている．

特に重度の精神疾患患者の判別には AUC 0.779 の精度を持つ [@Wake+2022]．

しかし，職業ストレス [@Mourad-Gaballah2023] のほかに，心不全，肝硬変，妊娠，スポーツなど種々の理由でもバイオピリンの尿中排出濃度が変化する．BMI （特にトリグリセリド）との相関も疑われている．

### バイオピリンレベルによるモニタリングの先行研究

臨床実習のある３回生の方が，４回生よりもバイオピリンレベルが高かった [@Tada+2020]．

[@高知恵+2023] でも質問票と尿中バイオピリンの双方を用いている．2022年の10月から12月末までのデータである．

しかし「調査当日の受け持ち褥婦数」を調べており，これでは２群間で有意差を認めなかったという結果であった．これには，「翌日から上昇する」という報告を引用して，もう少し時間を空けるべきであった可能性が指摘されている．


<!-- ::: {.callout-important appearance="simple" icon="false"}

* 人事に昇進の影響が違うと思われる．やはり **項目反応モデル** だろうか？
* そもそもココシルデータ解析は，「どのようなデータを取れば，有用な結論を導けるか？」というベイズ最適化的な側面があるかもしれない．
  * Big Five を取って，関連性が見れたらすごいことになる．
  * NEC が出している視線解析のベンチャーがある．尿検査のデータ以外も取れるかもしれない．

::: -->
