---
title: "民事訴訟法"
date: 3/11/2024
categories: [民訴法, まとめ]
abstract-title: 概要
abstract: 未整理
---


<h2 class="wp-block-heading" id="民事訴訟法の基本原理">民事訴訟法の基本原理</h2>



<h3 class="wp-block-heading" id="法律上の争訟概念と審判権の限界">法律上の争訟概念と審判権の限界</h3>



<ul>
<li>法律上の争訟（裁判所法3条1項）：<strong>当事者間の具体的な権利義務関係又は法律関係の存否に関する紛争であって、法令の適用によって最終的に解決することができる</strong>もの。<br>具体的事件性＋法適用可能性
<ul>
<li>宗教上の教義に関する判断</li>



<li>行政権・立法権の裁量権を尊重した制約</li>



<li>議員、内閣など他機関の自律権の尊重とその限界</li>
</ul>
</li>



<li>部分社会の法理（団体内部の自律権の尊重）
<ul>
<li>一般には「単なる内部事項と言えないような<span style="text-decoration: underline">重大な事項</span>又は<span style="text-decoration: underline">一般市民法秩序と関連する事項</span>は司法による審査の対象とし、その他のものについては内部事項として団体の自治に任すことが適当」である。</li>
</ul>
</li>
</ul>



<h3 class="wp-block-heading" id="訴権の濫用">訴権の濫用</h3>



<ul>
<li>請求が認容される事が明らかな場合の訴権の濫用
<ul>
<li>「甚だしく<strong>信義</strong>を欠き、道義上是認できず、かつ、&#8230;訴権の濫用に当たる」場合（長年訴訟提起していなかった、会社の支配権回復を目的としている、承認を得ることは容易だった）</li>
</ul>
</li>



<li>相手方当事者による主張立証の機会を妨げ、関与を排除する不適正な訴訟手続によって債務を負担させようとした場合<br>→<strong>信義</strong>を欠き、民事訴訟制度の制度趣旨、目的に照らして著しく相当性を欠く</li>



<li><span style="text-decoration: underline">訴訟上又は訴訟外において相手方当事者を困惑させることを目的とし、</span>訴訟が係属、審理されていること自体を社会的に誇示することにより、<span style="text-decoration: underline">相手方当事者に対し有形、無形の不利益・負担若しくは打撃を与えることを目的として提起された</span>ものであり、その訴訟を維持することが民事訴訟制度の趣旨、目的に照らして著しく相当性を欠き、<strong>信義</strong>に反する場合</li>
</ul>



<h3 class="wp-block-heading" id="不当訴訟">不当訴訟</h3>



<ul>
<li>「訴えの提起が相手方に対する違法な行為といえるのは、当該訴訟において<span style="text-decoration: underline">提訴者の主張した権利又は法律関係が事実的、法律的根拠を欠くものである上、提訴者がそのことを知りながら又は通常人であれば容易にそのことを知り得たといえるのにあえて訴えを提起した<strong>など</strong></span>、<strong>訴えの提起が裁判制度の趣旨目的に照らして著しく相当性を欠くものと認められる</strong>時」
<ul>
<li>事後的に不法行為と評価する関係では、既に訴権が行使されている（本案判決が出されている）ので、原告の裁判を受ける権利の剥奪を心配する必要はない。これに対して訴え却下（<strong>本案判決の拒絶</strong>）という効果を持つ訴権濫用の例においては裁判を受ける権利を剥奪することになりかねない。</li>



<li>訴権の濫用は本案判決の前に判断されるので、権利の存否に対して判断を下しにくい。行為の悪性・目的の悪性に焦点を置かざるを得ない。</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="当事者能力-任意的訴訟担当">当事者能力・任意的訴訟担当</h2>



<ul>
<li>当事者能力：民事訴訟の当事者となることのできる一般的な資格（訴訟の内容・性質に関係なく一般的に判定）
<ul>
<li>実体法上、権利義務の帰属主体となることができる者であることが必要。<br>→私法上権利能力を有する者は、訴訟物のなんたるかを問わず当事者能力がある（民訴法28条）</li>



<li><strong>「法人でない社団」（民訴29条）</strong>→私法上権利義務の主体たり得ない</li>
</ul>
</li>



<li>権利能力なき社団の当事者能力<br>「<span style="text-decoration: underline">団体としての組織</span>を備え、<span style="text-decoration: underline">多数決の原則</span>が行われ、<span style="text-decoration: underline">構成員の変更にかかわらず団体そのものが存続</span>し、その組織において<span style="text-decoration: underline">代表の方法、総会の運営、財産の管理その他団体としての主要な点が確定して</span>いなければならない」
<ul>
<li>財産の管理の位置付け
<ul>
<li>固定資産ないし基本的財産を有することは不可欠の要件ではないとする判例（平成14年）。</li>



<li>単なる例示に過ぎないとする見解、収支管理の体制があれば足りるとする見解も。</li>



<li>紛争管理事務との関係</li>
</ul>
</li>
</ul>
</li>



<li>権利能力なき社団の当事者適格の論理的根拠
<ul>
<li>社団は、社員に対して<strong>法定訴訟担当</strong>に当たるか？</li>



<li>任意的訴訟担当と言えるか？（法律構成の問題・管理処分権はどの時点で授権されているのか）</li>
</ul>
</li>



<li>民法上の組合の当事者能力
<ul>
<li>権利能力なき社団の4要件との関係</li>
</ul>
</li>



<li>明文なき<strong>任意的訴訟担当</strong>
<ul>
<li>弁護士代理の原則（民訴54条1項）：三百代言などの不明朗な職業の発生を一般的に防止すると共に、法律に昏い本人の利益保護を確実にし、かつ手続進行の円滑化を目的とする。</li>



<li>訴訟信託の禁止（信託法10条）</li>



<li>「弁護士代理の原則、訴訟信託の禁止といった制限を回避、潜脱するおそれがなく、かつ、これを認める合理的必要がある場合には許容するに妨げない」</li>
</ul>
</li>



<li><strong>選定当事者</strong>制度（民訴30条）
<ul>
<li>「共同の利益」：多数者相互の間において共同訴訟人となり得べき関係を有し、またはこれに対する各請求が主要な攻撃防御方法を共通にする</li>
</ul>
</li>



<li>権利能力なき社団と登記
<ul>
<li>代表者・登記名義人が当事者適格を有する根拠（信託的構成、登記手続請求訴訟を追行する権限の授与）</li>



<li>社団自身が当事者となった場合に、構成員に判決の効力が及ぶ根拠（115条1項各号）<br>※実体法上、登記請求権は帰属していないのに？</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="訴えの利益">訴えの利益</h2>



<ul>
<li>訴えの利益：紛争解決のために訴訟上の請求に対して判断をしてもらうための、すなわち<strong>本案判決を受ける正当な利益ないし必要性</strong>
<ul>
<li>当事者適格が訴えで特定された当事者に対して本案判決をすることの必要性・実効性を問題にするのに対して、訴えの利益は請求の内容自体に関して本案判決の必要性・実効性を問う。</li>
</ul>
</li>
</ul>



<h3 class="wp-block-heading" id="確認の利益">確認の利益</h3>



<ul>
<li>確認の利益の基準<br>①<strong>方法選択の適否</strong>　②<strong>対象選択の適否</strong>　③<strong>即時確定の利益</strong>
<ul>
<li>対象選択の適否：原則として、現在の積極的な法律関係を対象とするべき</li>



<li>即時確定の利益：<span style="text-decoration: underline">現に、原告の有する権利または法律的地位に危険または不安が存在し、これを除去するため被告に対して確認判決を得ることが必要かつ適切な場合</span>に認められる</li>
</ul>
</li>



<li>遺言無効確認訴訟の訴えの利益
<ul>
<li>判例では、事案によって認めたものと否定したものがある（遺言者の死亡前と死亡後での利益状況の違い）。</li>



<li>実質的に問題とされる権利関係は現在の権利関係か？</li>



<li><span style="text-decoration: underline">当事者の紛争の直接的な対象が「基本的法律行為」である場合</span>、過去の法律行為を対象とする方が抜本的。</li>



<li>受遺者たる地位（将来の訴えとして見た場合）<br>→「事実上の期待を有する地位」にすぎない。</li>
</ul>
</li>



<li>敷金返還請求権確認訴訟の訴えの利益
<ul>
<li>条件付きの権利と言えるか（他の将来発生する権利との違い）</li>
</ul>
</li>
</ul>



<h3 class="wp-block-heading" id="将来の給付の訴え-135条">将来の給付の訴え（135条）</h3>



<ul>
<li>判断枠組み
<ul>
<li>まず、当該請求権が、期限未到来の請求権や停止条件つき請求権、保証人の求償権のようにその基礎がすでに成立しているもののように<span style="text-decoration: underline">請求権の成否、内容を基礎づける事情があるか</span>を判断する。<br>（適格性の問題・<strong>発生の蓋然性と内容の確定性</strong>）</li>



<li>そして、あらかじめ給付判決を得ておく必要があるかという点からは、<span style="text-decoration: underline">現に将来において履行が期待できないということが確実になっている必要がある</span>（請求を基礎付ける要件の存続が高度の蓋然性を以て予測される）。（必要性の問題）</li>
</ul>
</li>



<li>将来の（継続的）不法行為に基づく損害賠償請求<br>①請求権の<strong>基礎となるべき事実関係及び法律関係</strong>が既に存在し、その継続が予測されるとともに、<br>②将来において請求権の存否または内容につき<strong>債務者にとって有利な事情の変動があることが明確に予測され</strong>、<br>③しかも、これについては<strong>請求異議の訴えによりその発生を証明してのみ執行を阻止しうるという負担を債務者に課しても格別不当とは言えない場合</strong>に限定される。<br>※権利の消滅等に関わる事情が債務者に関する事実に集中している時などは、立証が容易である。</li>



<li>将来の給付判決が確定した後の事情変更（一部請求？既判力の範囲？）</li>
</ul>



<h2 class="wp-block-heading" id="重複する訴えの提起禁止-142条">重複する訴えの提起禁止（142条）</h2>



<ul>
<li><strong>重複起訴の禁止（民訴142条）</strong>
<ul>
<li>趣旨：審理の判断の重複による訴訟不経済、既判力矛盾抵触、被告の応訴の煩</li>



<li><span style="text-decoration: underline">同一当事者間において、同一事件（訴訟物）に関する訴訟を提起した場合</span>には、原則としては訴えが重複していることになる。</li>



<li>請求の同一性までは要しない（反対形相の関係もOK）。</li>



<li>先行訴訟が控訴審に継続中である場合、口頭弁論が終結済みである（口頭弁論終結後は反訴の提起をすることができない・146条1項）などの事由により<span style="text-decoration: underline">新たに反訴の提起をすることがおよそ不可能な状態にあると認められる場合や、適法に反訴を提起することが極めて困難であると認められるような特段の事情がある場合において、当事者の権利実現・確保のために必要な時</span>には、その限度で、例外的に先行訴訟の継続中であっても新たな訴訟を提起することが許される余地があるものと解される。</li>
</ul>
</li>



<li>債務不存在確認と給付の訴え
<ul>
<li><strong>反訴</strong>として給付の訴えが提起されると、確認の利益（方法選択の適切性）が否定される。</li>



<li>反訴の場合には、142条に抵触しない。<br>（but 弁論が分離されずに審理されることにつき蓋然性があったことを以て初めて142条の趣旨に反するおそれがないと言えるのでは。）</li>
</ul>
</li>



<li>142条と<strong>相殺</strong>
<ul>
<li>既判力の矛盾抵触が生じる可能性がある部分については相殺の抗弁を排除しなければならない。</li>



<li>一部請求と相殺<br>①明示的一部請求の場合、残部については既判力が及ばないため、既判力の矛盾抵触の問題は生じない<br>②明示的一部請求が一部認容判決とされた場合に残部請求をすることは信義則に反するため認められないことから、<span style="text-decoration: underline">後訴での相殺の抗弁の主張を許すことは事実上の判断の抵触が生じ得る</span>が、相殺の抗弁の<strong>防御権的性格、相殺の簡易決済機能、担保的機能</strong>に照らし、正当な防御権の行使として特段の事情のない限り認められると述べ、 後訴での相殺の抗弁の主張を認めた。</li>



<li>最判平成18年4月14日<br>反訴請求債権を自働債権とし、本訴請求債権を受働債権とする相殺の抗弁の主張は、「反訴原告において異なる意思表示をしない限り、反訴は、<span style="text-decoration: underline">反訴請求債権につき本訴において相殺の自働債権として既判力ある判断がされた場合にはその部分については反訴請求しない趣旨の<strong>予備的反訴</strong></span>に変更されることになる」とした。<br>→弁論の分離可能性を排除</li>



<li>最判令和2年9月11日<br>予備的反訴への変更というロジックを使わずに弁論の分離可能性を排除した。
<ul>
<li>反訴請求債権を受働債権とする相殺の抗弁が主張されたときは、<strong>相殺による清算的調整を図るべき要請</strong>（相殺による清算的調整を図ることが当事者双方の便宜と公平にかない、法律関係を簡明にする）が強いものといえる。</li>



<li><strong>それにもかかわらず</strong>，これらの本訴と反訴の弁論を分離すると、本訴請求債権の存否等に係る判断に矛盾抵触が生ずるおそれがあり、また、審理の重複によって訴訟上の不経済が生ずるため、このようなときには、両者の弁論を分離することは許されないというべき。</li>
</ul>
</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="弁論主義">弁論主義</h2>



<ul>
<li>弁論主義：<span style="text-decoration: underline">判決の基礎を成す事実の認定に必要な訴訟資料の提出</span>（主要事実の主張と必要な証拠の申出）を当事者の権能と責任とする建前</li>



<li>第三原則
<ul>
<li>第1原則（主張責任ルール）：主要事実は<span style="text-decoration: underline">当事者が口頭弁論で陳述しない限り</span>判決の基礎に採用することができない。</li>



<li>第2原則（自白ルール）：<span style="text-decoration: underline">当事者間に争いのない事実</span>は、証拠によって認定する必要がない（179条・159条１項）のみならず、これに反する認定をすることができない。
<ul>
<li>自白（審判排除効をもつ）＝<strong>相手方の主張する自己に不利益な事実を争わない旨の意思を表明する陳述</strong></li>



<li>裁判所に対する拘束力（弁論主義・第2テーゼ/審判排除効）<br>→当事者は証明する必要がない（179条・不要証効）<br>→当事者に対する拘束力（不撤回効・自己責任/禁反言の原則）</li>



<li>第3原則（証拠申請ルール）：<span style="text-decoration: underline">争いのある主要事実</span>は証拠により認定するが、証拠は原則として当事者が申請したものでなければならない。</li>
</ul>
</li>
</ul>
</li>



<li>対象が<strong>主要事実</strong>に限定される理由
<ul>
<li><span style="text-decoration: underline">当事者意思の尊重、不意打ち防止</span>の見地から、訴訟の勝敗に直結する主要事実を弁論主義の対象とすれば十分である。</li>



<li><span style="text-decoration: underline">間接事実や補助事実は主要事実の認定につき証拠と共通の機能を果たす</span>ところ、これらにつき主張責任や自白の拘束力を認めるのは自由心証主義に反する。</li>
</ul>
</li>



<li><strong>釈明義務</strong>・法的観点指摘義務
<ul>
<li><span style="text-decoration: underline">訴訟指揮権（民事訴訟法148条）</span>の一作用として当事者に働きかけることができる。</li>



<li>当事者のした不明瞭な申し立てや主張等を問いただすという消極的釈明義務は果たさなければならないとするのが一般的だが、<span style="text-decoration: underline">積極的釈明（適当な申し立て・主張をしない場合に、裁判所がそれを示唆・指摘すること）については権能の過度の行使は、事案の真相を曲げ、当事者間の公平を害する恐れ</span>がある。
<ul>
<li>裁判の結果に重大な影響を与える蓋然性</li>



<li>当事者自治の可能性・期待可能性</li>



<li>釈明により紛争の抜本的解決が可能となったか</li>



<li>中立を害するかどうか</li>
</ul>
</li>



<li>弁論主義の形式的な適用による不合理を修正し、適正にして迅速公平な裁判を可能にする。</li>
</ul>
</li>



<li>判決効
<ul>
<li>既判力が生じている部分だとしても、例外的に前訴で解決されたとの期待がない部分については、後訴で主張しても紛争の蒸し返しにならないのでは？（いわゆる<strong>既判力の縮減</strong>を判決は否定）</li>
</ul>
</li>



<li>主張の具体化・事実解明義務論
<ul>
<li>行政のアカウンタビリティー</li>



<li>経験則による事実上の推認（伊方原発訴訟）</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="証明責任の軽減">証明責任の軽減</h2>



<ul>
<li>過失の一応の推定
<ul>
<li>高度の蓋然性を備える経験則→前提事実の主張立証を以て事実上の推定が働く</li>
</ul>
</li>



<li>概括的・選択的認定</li>



<li>248条：損害賠償額の認定
<ul>
<li>証明度の軽減vs. 裁判所の裁量評価？</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="文書提出命令">文書提出命令</h2>



<ul>
<li>文書化の利益＝表現形態選択の利益＋表現形態固定の利益
<ul>
<li>一般義務化しても、証人義務（190条）に比べて狭い。</li>
</ul>
</li>



<li><strong>自己利用文書</strong>（220条4号二）e.g., 貸出稟議書
<ul>
<li>①ある文書が，その<span style="text-decoration: underline">作成目的，記載内容，これを現在の所持者が所持するに至るまでの経緯，その他の事情</span>から判断して，<strong>専ら内部の者の利用に供する目的</strong>で作成され，<strong>外部の者に開示することが予定されていない</strong>文書であって，
<ul>
<li>作成義務が法定されているか？（監督官庁への提出の可能性）</li>



<li>忌憚のない意見・評価</li>
</ul>
</li>



<li>②開示されると<strong>個人のプライバシー</strong>が侵害されたり個人ないし<strong>団体の自由な意思形成</strong>が阻害されたりするなど，開示によって<span style="text-decoration: underline">所持者の側に看過し難い不利益</span>が生ずるおそれがあると認められる場合</li>



<li>③特段の事情がない限り、（自己利用文書にあたる。）
<ul>
<li>文書提出の申立人が文書所持者と同視することができる場合（①の例外）</li>



<li>文書所持者が変わって害される利益がない場合（②の例外・ただし場面を限定すべき）</li>
</ul>
</li>
</ul>
</li>



<li><strong>技術又は職業の秘密</strong>（220条4項ハ・197条1項3号）
<ul>
<li>「技術又は職業の秘密」とは、その事項が公開されると、<span style="text-decoration: underline">当該技術の有する社会的価値が下落しこれによる活動が困難になるもの</span>又は<span style="text-decoration: underline">当該職業に深刻な影響を与え以後その遂行が困難になるもの</span>をいうと解するのが相当である。</li>



<li>守秘義務との関係（医師や弁護士は異なるか？）</li>



<li>職業の秘密に該当するかを判断したのち、職業の秘密に当たるとしても、比較衡量によって保護に値する情報かどうかを判断↓<br>当該事項が保護に値するかどうかは、それが公表されることによって受ける<strong>秘密保持者の不利益</strong>と拒絶によって具体的訴訟が受ける<strong>真実発見と裁判の公正</strong>にとってのマイナス効果とを比較衡量して判断される。</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="判決効の客観的範囲">判決効の客観的範囲</h2>



<ul>
<li>既判力の正当化根拠：当事者が手続上対等にその訴訟物たる権利関係の存否について弁論し、訴訟追行する権能と機会とを保障されたことに求められる。<br>=「<strong>手続保障に基づく自己責任</strong>」</li>



<li><strong>既判力の時的限界</strong>：事実審の口頭弁論終結時</li>



<li><strong>既判力の物的限界（客観的範囲）</strong>
<ul>
<li>判決主文中の判断（114条1項）判決理由中の判断には既判力は原則として生じない。</li>



<li>例外としての相殺についての判断（114条2項）：請求の当否の判断をするのに反対債権の存否を実質的に判断する必要があった場合に既判力が生じる。</li>
</ul>
</li>



<li>争点効
<ul>
<li>①主要な争点について、②十分な主張・立証を尽くした場合において、③裁判所が実質判断をした時、④係争利益がほぼ同一である後訴において、当事者は争点となる<strong>事実</strong>についての裁判所の判断に拘束される</li>



<li>114条1項の趣旨に反しないと解釈する余地
<ul>
<li><span style="text-decoration: underline">手続上保障された相手方の主張を争う機会と権能を既に利用した者が相手方に負う結果責任</span>として、その蒸し返しを禁じ、一方で出された結論を他方の請求の審判にもそのまま通用させることが当事者間の公平にかなうといえ、これは同項の趣旨に反するものではない。</li>



<li>また、裁判所の立場から見ても、既判力を主文の判断に限定することによって確保した攻撃防御方法についての<span style="text-decoration: underline">審判方法の弾力性を損なうものではない</span>。</li>
</ul>
</li>
</ul>
</li>



<li>既判力に準ずる効力
<ul>
<li>前訴の訴訟物は、直接的には給付請求権の存否及びその範囲。そのため、限定承認の存在・効力は訴訟物とならず、既判力は生じない。<br>しかし、<span style="text-decoration: underline">限定承認の存在・効力もこれに準ずるものとして審理されて、これが認められる時には留保として主文に明示される（かなり訴訟物に近い判断）</span>。よって、<strong>前訴における限定承認の存在・効力に係る判断には既判力に準ずる効力</strong>が生じる。</li>
</ul>
</li>



<li>信義則による遮断（考慮要素は違い得る）
<ul>
<li>紛争の蒸し返しと言えるか</li>



<li>前訴で主張することが容易であったか、期待されたか</li>



<li>相手方に紛争が最終的に決着したとの信頼を持たせていたか（前訴からの時間的な間隔）、権利失効の原則</li>



<li>禁反言の原則に反すると言えるか（端的に主張が異なっているというだけではなく、当該主張が前訴でどのように主張されているかも重要）</li>



<li>当事者の立場（防御的な立場にあるか）</li>
</ul>
</li>



<li>一部請求
<ul>
<li>明示的一部請求の場合の訴訟物（残部の取り扱い）</li>



<li>分割債務と連帯債務</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="判決効の主観的範囲">判決効の主観的範囲</h2>



<ul>
<li>対立する<span style="text-decoration: underline">当事者間</span>にだけ作用するのが原則。</li>



<li><strong>訴訟担当</strong>の場合の被担当者（115条1項2号）
<ul>
<li>隠れた当事者ともいうべき訴訟物たる利益の帰属主体に、この者が自分で訴訟をしたのと同じともいうべき訴訟物たる利益の帰属主体に、この者が自分で訴訟をしたのと同じ効力を及ぼす。</li>
</ul>
</li>



<li>「口頭弁論終結後の<strong>承継人</strong>」（同項3号）
<ul>
<li>基準時後に利害関係を持つに至った者が、当事者間における紛争解決の結果を自由に争えるとすれば敗訴した当事者がその訴訟物たる権利関係を第三者に処分することによって、簡単に訴訟による解決の結果を無駄にできてしまう（→紛争解決の実効性）から。</li>



<li><strong>前訴で解決された紛争及びそれから派生した紛争の主体たる地位を、基準時後に取得した者</strong>
<ul>
<li>基準時以降に権利義務を承継した者（原始取得・承継取得）・当事者適格を獲得した者</li>
</ul>
</li>



<li>承継人が自身に固有の防御方法を主張することは妨げられない。</li>
</ul>
</li>



<li>当事者、被担当者またはそれらの承継人のために「請求の目的物を所持する者」（同項4号）
<ul>
<li>その特定物の所持につき<strong>固有の利益を持たず</strong>、<strong>専らこれを当事者またはその承継人のために所持している</strong>者（受寄者・同居人）は、当事者の受けた判決の規範力に拘束される。</li>
</ul>
</li>



<li><strong>反射効</strong>：既判力の主観的拡張（115条各号の当事者以外）
<ul>
<li>実体法上の関係を訴訟上にも反映させて、紛争の具体的な解決結果においても実体法上の関係に反しないようにする→紛争の統一的な解決</li>



<li>実質的な紛争の蒸し返しを回避する</li>
</ul>
</li>



<li>各事例においてどのような立場をとるか？（論証）
<ul>
<li>主債務者と保証人</li>



<li>連帯債務者間</li>



<li>借地人と土地上の建物の賃借人</li>



<li>債権者代位における債権者間</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="訴訟上の和解-請求の認諾-放棄">訴訟上の和解（請求の認諾・放棄）</h2>



<ul>
<li>訴訟上の和解の効力（既判力を認めるか？判例は制限的既判力説だとされるが&#8230;）
<ul>
<li>和解当事者の意思表示の瑕疵</li>



<li>争う方法（再審が必要か？）</li>
</ul>
</li>



<li>訴訟上の和解の法的性質
<ul>
<li>私法行為説、訴訟行為説、両性説、併存説</li>



<li>両者は依存関係にあるか？（片面的な立場も）</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="訴訟承継等">訴訟承継等</h2>



<h3 class="wp-block-heading" id="訴訟承継">訴訟承継</h3>



<ul>
<li>制度目的
<ul>
<li>従前の訴訟に承継人を引き込んだ方が紛争の実効的解決を図ることができる・当事者や裁判所は、従前の裁判資料を使える（<strong>訴訟経済・効率性</strong>）</li>



<li>訴訟承継がないとすると、訴訟外の実体関係の変動によって、当事者が今まで有利に進めてきていた訴訟状態がチャラになってしまう（<strong>当事者間の公平</strong>・<strong>既得的地位の保護</strong>）</li>
</ul>
</li>



<li><strong>紛争の主体たる地位</strong>の承継の意義
<ul>
<li>権利義務の移転でない場合もあり得る。当事者適格の移転に留まらない？</li>



<li>「紛争の主体たる地位」とは実体法上の権利義務の帰属点として理解されているのではなく、むしろ経済的利害対立のある当事者として捉えられるのでは？</li>



<li>新堂説による要件の具体化<br><strong>争点の共通性</strong>⇦訴訟の効率化<br><strong>何らかの依存関係</strong>⇦当事者間の公平</li>
</ul>
</li>



<li>承継原因発生時の訴訟状態を引き受ける
<ul>
<li>必要性 ①相手方の既得的地位の維持・保障　（これに伴う訴訟経済）②元々承継人を引き込んでおく手段がない</li>



<li>許容性①依存的関係にあるのだから、従前訴訟の紛争に関する訴訟状態をも引き継がなければならない<br>②承継人のための訴訟追行も従前訴訟の当事者によって代行されている</li>
</ul>
</li>



<li>承継原因発生〜引受決定までの訴訟行為について
<ul>
<li>訴訟原因発生後の訴訟行為は、承継人に及ばない</li>



<li>訴訟状態承認義務の趣旨</li>
</ul>
</li>



<li>参加承継と引受承継
<ul>
<li>参加承継の場合、49条又は51条が準用する40条が適用され、<strong>必要的共同訴訟</strong>と同様の規律が働く。従前訴訟の当事者が行った訴訟行為の効果が及ぶ。</li>



<li>引受承継の場合、50条又は51条が準用する41条1項・3項が準用され、<strong>同時審判の申出がある訴訟</strong>と同様の規律が働く（要は<span style="text-decoration: underline">通常共同訴訟</span>と同じ）。
<ul>
<li>従前訴訟の当事者が行った訴訟行為の効果は当然には及ばない（共同訴訟人独立の原則）。</li>



<li>41条が準用されているので、弁論及び裁判は分離しないでしなければならない。一部判決もできない。</li>
</ul>
</li>



<li>引受承継の場合、Yは自分が両負けする危険を防ぐためにZを引き込んでいる（この場合、通常共同訴訟で弁論・裁判が分離されるのを回避することさえできれば目的は達成されるので、目的の達成のためには41条の適用があれば十分であり、40条を適用するのは若干過度な感じがある）<br>同じ裁判体であれば、同じ裁判官・訴訟資料によって判断されるからYにとって両負けの判決は出されない。</li>



<li>参加承継の場合、Zが積極的に入っていれば、Zの思惑が引受承継の時と異なる。YがXの請求を認諾してしまい、その効力が当然に及ぶとすると、Zにとっては望ましくない（XZ間の請求の判断がZY間の請求の判断に影響するだろう）。そうすると、41条だけでは不足があるから、40条によってそれを妨げる権能を認める必要がある。</li>
</ul>
</li>
</ul>



<h3 class="wp-block-heading" id="独立当事者参加">独立当事者参加</h3>



<ul>
<li>「三当事者間の法律関係を合一に確定させることを目的とする訴訟において、そのうちの<span style="text-decoration: underline">二当事者のみの間において当該訴訟物について裁判上の和解をする</span>ことは、三者間の合一確定の目的に反するから許されないものと解すべき」（東京高判平成3年12月17日）<br>→あらゆる場合に妥当するか？
<ul>
<li><strong>三当事者間の牽制関係</strong>（片面訴訟参加もできることを理由に、こちらの考え方につく論者が優勢）
<ul>
<li>必要的共同訴訟の場合には、共同訴訟人間の連合関係を訴訟追行に反映するべく、40条1項〜3項が適用されているが、独立当事者参加の場合にこれらの規定が準用されるのは、<span style="text-decoration: underline">どの当事者もそれぞれに対立関係にあって、自分を除外して他の二人だけで勝手に自分に不利な訴訟追行がなされることを阻止・牽制する必要があって、この相互の排斥関係を反映させる</span>ためである。</li>



<li>したがって、二当事者間の訴訟行為は、他の1人に不利益をもたらすかぎり、この者に対して効力を生じないが（40条1項の準用）、その二当事者間では効力が生じるに止まるのではないか？<br>or 他の権利主張者の利益を害するような和解はできないが、内容が他の当事者に不利益を与えなければ有効と解する余地もあるのではないか？</li>
</ul>
</li>
</ul>
</li>



<li>合一確定の必要性→<strong>確定遮断効</strong>
<ul>
<li>不利益変更・利益変更は合一確定の必要性の限度で認められる（ただし、その限度はよく考えるべき）。</li>
</ul>
</li>
</ul>



<h2 class="wp-block-heading" id="相殺と不利益変更の禁止">相殺と不利益変更の禁止</h2>



<ul>
<li>一部請求
<ul>
<li>明示的一部請求の判決確定後の残部請求は妨げられない。<br>∵先行する明示的一部請求の訴訟物は、明示された債権の一部のみであって、その部分にしか既判力が生じない（114条1項）
<ul>
<li>ただし、明示的一部請求全部又は一部の棄却の後の残部請求は、<span style="text-decoration: underline">信義則に反して</span>認められない。<br>∵紛争の蒸し返し＋被告の紛争解決に対する合理的期待に反する（ただし、合理的期待を認めるかは議論の余地あり）</li>
</ul>
</li>



<li>明示がなかった場合には、全額が訴訟物となっていると解されて、改めて同一債権につき請求した場合には、既判力の遮断効によって訴え却下判決が出される。</li>
</ul>
</li>



<li>一部請求と過失相殺
<ul>
<li>「<span style="text-decoration: underline">損害の全額から過失割合による減額をし、</span>その残額が請求額をこえないときは右残額を認容し、残額が請求額をこえるときは請求の全額を認容することができる」（外側説）</li>



<li><strong>当事者の通常の意思に合致する</strong>（通常の当事者は、一部請求する場合には総額から相殺されて一部が消滅するとしても、最低限請求額は認められるだろうとの期待を予め持って請求しているので、一部請求額から減額すると当事者の合理的意思に反することになる）。</li>
</ul>
</li>



<li>一部請求と相殺の抗弁
<ul>
<li>既判力が及ぶ範囲</li>
</ul>
</li>
</ul>