---
title: "商法［司法試験対策］"
date: 2/10/2024
categories: [商法, 司法試験対策]
---

## R5

* 423条1項・429条の取締役の責任：任務懈怠
    * 唯一の株主であり、取締役でもあった場合
    * 株主の経済的利益最大化の原則の限界？^[田中亘「株主第一主義の合理性と限界(上)（下）」法律時報92巻5号123頁、92巻7号79頁（2020）]
* 総株主による責任免除（424条）
* 株主総会決議取消の訴えの利益
    * 瑕疵の連鎖
    * 権利（代表）取締役：346条、351条
* 株式を共同相続した場合の権利行使者の指定（106条）


## R4


* 取締役の任期を短縮する定款変更
    * 取締役の地位を失った者による損害賠償請求
* 親会社の圧力の下でいわゆるデュー・ディリジェンスを行うことなく事業を譲り受けたことに関する取締役の任務懈怠責任
    * 構造的な利益相反
* 事業を譲渡した会社（譲渡会社）の商号の一部が含まれている商標を使用した場合における事業を譲り受けた会社（譲受会社）の責任（会社法22条）

## R3


* 利益相反取引（間接取引）
    * 取引の有効性について判例に従って適切に論じる
* 多額の借財
* 実質的な株式引受人
    * 形式説と実質説の論理的な理由づけ
* 代表取締役の権限に対する制限（349条5項）
* 議決権の代理行使（310条1項）

## R2

* 新株発行の無効の訴え
    * 非公開会社における特別決議を経ないでなされた株式発行の効力
    * 有利発行→理由の説明（199条3項）、招集通知への記載（299条2項2号・取締役会設置会社、298条1行2号、規則63条7号ホ）
    * 株主総会決議における取消事由と無効原因との関係
* 株式併合に先立つ対処法
    * 差止め請求（種類株主としての116条1項関連⇄182条の4 ※適用のための要件が異なるので注意）
    * 反対株主による株式買取請求
    * 株主総会決議に取消事由があることを無効原因とする

## R1

* 少数株主による議題提案権（303条1項）など、少数株主が取ることができる手段の具体的比較
* 買収防衛策としての新株予約券の無償割当て
    * 株主平等原則（の趣旨）との関係
    * 不公正発行にあたるか（主要目的ルール＋α）
* 取締役の責任（423条1項）
    * 株主総会決議に対する遵守義務と、会社の利益を保護する義務との関係
